/* verify_panel_release_workflow — the guarded lane that publishes a panel
   release through the private database bridge without console work.

   The dangerous half is SQL generated by
   .github/scripts/generate_panel_release_sql.sh and applied once against
   production, so that script is executed here against a real scratch
   database carrying the tracked schema, as the NOBYPASSRLS runtime role the
   service itself connects with — the exact conditions of the one-shot run.

   Pinned contracts:
   A) Lane guards in .github/workflows/panel-release.yml: dispatch-only, the
      typed RELEASE confirmation, read-only repo permissions, the shared
      production concurrency group, verify-ca, the masked runtime credential,
      the firewall-rule cleanup, and the repository tree as the only release
      authority (no version/sha inputs; rebuilt artifact must equal the
      tracked pins; the package battery runs). The CCX never escapes the
      runner: no upload-artifact, no artifact URL.
   B) The generator refuses bad callers: a non-semantic version, an artifact
      whose bytes do not equal the declared SHA-256/size, a minimum newer
      than the release — each a named refusal, never SQL.
   C) Applied to a real schema-carrying database, the generated SQL lands the
      artifact as verified 'ready' chunks (the reassembled digest equals the
      pin), points the policy at exactly one enabled latest and one minimum,
      and the server's own gate math then allows the released version while
      still requiring updates from an older install.
   D) A second run of the same SQL is a no-op that keeps a single latest; a
      policy whose minimum has no release record aborts inside the
      transaction and changes nothing.

   This deliberately uses a real PostgreSQL server. CI supplies PostgreSQL
   16; locally, point PGHOST/PGPORT/PGUSER/PGPASSWORD at an administrator
   that may create scratch roles and databases.

   Usage: node test/verify_panel_release_workflow.js */
"use strict";

const crypto = require("crypto");
const fs = require("fs");
const os = require("os");
const path = require("path");
const { spawnSync } = require("child_process");

const ROOT = path.join(__dirname, "..");
const WORKFLOW = fs.readFileSync(path.join(ROOT, ".github/workflows/panel-release.yml"), "utf8");
const GENERATOR = path.join(ROOT, ".github/scripts/generate_panel_release_sql.sh");
const RELEASE_MANIFEST = JSON.parse(fs.readFileSync(path.join(ROOT, "panel/release-manifest.json"), "utf8"));
const VERSION_POLICY = JSON.parse(fs.readFileSync(path.join(ROOT, "docs/download/panel-version.json"), "utf8"));
const { evaluatePanelVersion } = require("../server/lib/panel-versions");

const SUFFIX = String(process.pid);
const DB = "hnk_release_probe_" + SUFFIX;
const RUNTIME = "hnk_release_runtime_" + SUFFIX;
const PASSWORD = "release-workflow-probe";
const ADMIN_UUID = "cccccccc-0000-4000-8000-000000000001";
const CHUNK_BYTES = 65536; // the smallest legal geometry, to exercise multi-chunk assembly

const ADMIN_ENV = Object.assign({}, process.env, {
  PGHOST: process.env.PGHOST || "127.0.0.1",
  PGPORT: process.env.PGPORT || "5432",
  PGUSER: process.env.PGUSER || "postgres",
  PGPASSWORD: process.env.PGPASSWORD || "postgres",
  PGCLIENTENCODING: "UTF8",
});
delete ADMIN_ENV.PGOPTIONS;
const RUNTIME_ENV = Object.assign({}, ADMIN_ENV, { PGUSER: RUNTIME, PGPASSWORD: PASSWORD });
const SERVICE_CONTEXT =
  "select set_config('request.role','service_role',false), " +
  "set_config('request.jwt.claim.sub','',false), " +
  "set_config('request.is_admin','false',false), " +
  "set_config('request.user_email','',false)";

let failures = 0;
function report(name, ok, detail) {
  console.log((ok ? "PASS" : "FAIL") + " — " + name +
    (ok ? "" : "  :: " + JSON.stringify(detail)));
  if (!ok) failures++;
}

function psql(args, env = ADMIN_ENV) {
  const child = spawnSync("psql", ["-X", "-v", "ON_ERROR_STOP=1", "-q", "-t", "-A"].concat(args), {
    env, encoding: "utf8", maxBuffer: 64 * 1024 * 1024,
  });
  const output = ((child.stdout || "") + (child.stderr || "")).trim();
  if (child.error) return { ok: false, out: child.error.message };
  return { ok: child.status === 0, out: output };
}
const sql = (text, db = "postgres") => psql(["-d", db, "-c", text]);
function serviceSql(text) {
  const result = psql(["-d", DB, "-c", SERVICE_CONTEXT, "-c", text], RUNTIME_ENV);
  const lines = result.out.split(/\r?\n/);
  return { ok: result.ok, out: lines.slice(1).join("\n").trim() };
}

function runGenerator(env) {
  return spawnSync(GENERATOR, [], {
    env: Object.assign({}, process.env, env),
    encoding: "utf8", maxBuffer: 128 * 1024 * 1024,
  });
}

function cleanup() {
  sql(`select pg_terminate_backend(pid) from pg_stat_activity where datname='${DB}'`);
  sql(`drop database if exists "${DB}"`);
  sql(`drop role if exists "${RUNTIME}"`);
}

/* ---- A) lane guards, pinned as text ---- */
report("the lane runs only on workflow_dispatch",
  /on:\s*\n\s+workflow_dispatch:/.test(WORKFLOW) &&
  !/\bpush:|\bpull_request:|\bschedule:/.test(WORKFLOW), "trigger set changed");
report("the typed confirmation RELEASE gates every run",
  WORKFLOW.includes('"$CONFIRM_INPUT" != "RELEASE"'), "typed confirmation missing");
report("the lane's repository permissions are read-only",
  /permissions:\s*\n\s+contents: read/.test(WORKFLOW) && !/contents: write/.test(WORKFLOW),
  "permissions widened");
report("production lanes stay serialized through one concurrency group",
  WORKFLOW.includes("group: digitalocean-production-secrets"), "concurrency group changed");
report("the only dispatch inputs are the action and the confirmation",
  !/inputs\.(?!action\b|confirm\b)[a-z_]+/i.test(WORKFLOW),
  "a new dispatch input could override the tracked release pins");
report("the release pins come from the tracked manifests",
  WORKFLOW.includes("panel/release-manifest.json") &&
  WORKFLOW.includes("docs/download/panel-version.json") &&
  WORKFLOW.includes("jq -r '.version' panel/manifest.json"), "pin source changed");
report("a rebuilt artifact that misses the pins is refused",
  WORKFLOW.includes("does not match panel/release-manifest.json"), "pin refusal missing");
report("the full package validation battery runs against the rebuild",
  WORKFLOW.includes("node test/verify_ccx_package.js"), "verify_ccx_package no longer runs");
report("the SQL comes from the tested generator script",
  WORKFLOW.includes(".github/scripts/generate_panel_release_sql.sh"), "generator not used");
report("the CCX is never uploaded out of the runner",
  !/upload-artifact/.test(WORKFLOW), "the private artifact must not become a run download");
report("the database connection verifies the cluster CA",
  WORKFLOW.includes("sslmode=verify-ca"), "TLS verification weakened");
report("the runtime credential is masked and never echoed",
  WORKFLOW.includes('echo "::add-mask::$RPASS"') &&
  !/echo\s+"?\$(URI|RUNTIME_URI|RPASS)\b/.test(WORKFLOW), "credential handling changed");
report("the temporary trusted-source rule is removed on exit",
  WORKFLOW.includes("trap cleanup_release EXIT") && WORKFLOW.includes("firewalls remove"),
  "firewall cleanup missing");
report("the Space mirror uploads through the tested helper and verifies round-trip",
  WORKFLOW.includes(".github/scripts/put_panel_object.js"), "mirror helper not used");
report("the mirror's ephemeral upload key is deleted on every exit path",
  WORKFLOW.includes("trap cleanup_mirror EXIT") &&
  WORKFLOW.includes("/v2/spaces/keys/$MIRROR_KEY_ACCESS"), "ephemeral key cleanup missing");
report("a missing Space stands the mirror down instead of failing the release",
  WORKFLOW.includes("the release stays on the database bridge"), "graceful stand-down missing");
report("only a content-addressed object key is accepted from the mirror",
  WORKFLOW.includes("(ccx/*)"), "object key shape check missing");
// A production token that keeps its identity but loses a scope is the failure
// this lane actually met (2026-09-01): doctl answered `databases list` with
// {"errors":[...],"status":403} and the old one-liner died as
// `jq: error (at <stdin>:1): Cannot index array with string "name"`, naming
// nothing an operator could act on. Both refusals must name themselves.
report("a list the token may not read is a named refusal, not a jq crash",
  (WORKFLOW.match(/jq -e 'type == "array"'/g) || []).length === 2 &&
  WORKFLOW.includes("refusing database reads") &&
  WORKFLOW.includes("refusing app reads") &&
  WORKFLOW.includes("DigitalOcean said:") &&
  !/doctl databases list --output json \| jq/.test(WORKFLOW) &&
  !/APPS_JSON="\$\(doctl apps list --output json\)"/.test(WORKFLOW),
  "a doctl list still flows straight into jq");
report("a refused Spaces credential reports its HTTP status and the lost scope",
  WORKFLOW.includes("-w '\\n%{http_code}'") &&
  WORKFLOW.includes("(401|403)") &&
  WORKFLOW.includes("no longer carries write scope") &&
  !/curl -fsS[^\n]*\/v2\/spaces\/keys"/.test(WORKFLOW),
  "the Spaces key creation still collapses every refusal into curl exit 22");

/* ---- build the real artifact once ---- */
const releaseDir = fs.mkdtempSync(path.join(os.tmpdir(), "hnk-release-probe-"));
const artifactName = `HNK_Ai_Panel_v${RELEASE_MANIFEST.version}.ccx`;
const artifactPath = path.join(releaseDir, artifactName);
const packaged = spawnSync(path.join(ROOT, "panel/package.sh"), [artifactPath], { encoding: "utf8" });
report("panel/package.sh rebuilds the release artifact", packaged.status === 0,
  (packaged.stderr || "").trim().slice(0, 200));
if (packaged.status !== 0) process.exit(1);
const artifactBytes = fs.readFileSync(artifactPath);
const artifactSha = crypto.createHash("sha256").update(artifactBytes).digest("hex");
const baseEnv = {
  VERSION: RELEASE_MANIFEST.version,
  ARTIFACT: artifactName,
  EXPECTED_SHA: artifactSha,
  EXPECTED_BYTES: String(artifactBytes.length),
  MINIMUM: VERSION_POLICY.minimum_supported_version,
  ARTIFACT_PATH: artifactPath,
  CHUNK_BYTES: String(CHUNK_BYTES),
};
report("the deterministic rebuild equals the tracked release pins",
  artifactSha === RELEASE_MANIFEST.sha256 && artifactBytes.length === RELEASE_MANIFEST.bytes,
  { measured: artifactSha.slice(0, 12), pinned: String(RELEASE_MANIFEST.sha256).slice(0, 12) });

/* ---- B) generator refusals ---- */
let refused = runGenerator(Object.assign({}, baseEnv, { VERSION: "6.25", ARTIFACT: "HNK_Ai_Panel_v6.25.ccx" }));
report("B1: a non-semantic version is refused",
  refused.status === 64 && !/insert into/.test(refused.stdout || ""), refused.status);
refused = runGenerator(Object.assign({}, baseEnv, { EXPECTED_SHA: "0".repeat(64) }));
report("B2: an artifact that does not equal the declared digest is refused",
  refused.status === 65 && !/insert into/.test(refused.stdout || "") &&
  /refusing to emit SQL/.test(refused.stderr || ""), refused.status);
refused = runGenerator(Object.assign({}, baseEnv, { MINIMUM: "99.0.0" }));
report("B3: a minimum newer than the release is refused",
  refused.status === 64 && /locks the release out/.test(refused.stderr || ""), refused.status);
refused = runGenerator(Object.assign({}, baseEnv, { OBJECT_KEY: "../not/a/key" }));
report("B4: a malformed Space object key is refused",
  refused.status === 64 && /OBJECT_KEY is malformed/.test(refused.stderr || "") &&
  !/insert into/.test(refused.stdout || ""), refused.status);

/* ---- C, D) against the real tracked schema ---- */
(async () => {
  cleanup();
  let r = sql(`create role "${RUNTIME}" login password '${PASSWORD}' nosuperuser nobypassrls nocreatedb`);
  if (r.ok) r = sql(`create database "${DB}" owner "${RUNTIME}"`);
  if (!r.ok) { report("scratch role and database", false, r.out.slice(0, 300)); process.exit(1); }

  const migrated = spawnSync("node",
    ["-e", 'require("./lib/migrate").migrate().then(()=>process.exit(0),e=>{console.error(e.message);process.exit(1);});'],
    {
      cwd: path.join(ROOT, "server"),
      env: Object.assign({}, ADMIN_ENV, {
        PGSSLMODE: "disable", ALLOW_UNVERIFIED_DB_TLS: "1",
        DATABASE_URL: `postgres://${RUNTIME}:${PASSWORD}@${ADMIN_ENV.PGHOST}:${ADMIN_ENV.PGPORT}/${DB}`,
      }),
      encoding: "utf8", maxBuffer: 10 * 1024 * 1024, timeout: 180000,
    });
  if (migrated.status !== 0) {
    report("scratch database carries the tracked schema", false,
      ((migrated.stdout || "") + (migrated.stderr || "")).split(/\r?\n/).slice(-4));
    cleanup(); process.exit(1);
  }
  report("scratch database carries the tracked schema", true);

  r = serviceSql(`
    insert into public.hnk_auth_users (id, email, encrypted_password, email_confirmed_at)
    values ('${ADMIN_UUID}', 'owner-release-probe@example.com', 'scrypt$16384$8$1$AAAA$AAAA', now());
    insert into public.profiles (id, email, name, is_admin)
    values ('${ADMIN_UUID}', 'owner-release-probe@example.com', 'Owner', true);
    insert into public.user_roles (user_id, role_id)
    select '${ADMIN_UUID}', id from public.roles where name = 'admin'
    on conflict do nothing;`);
  if (!r.ok) { report("seeded administrator", false, r.out.slice(0, 300)); cleanup(); process.exit(1); }

  const generated = runGenerator(baseEnv);
  report("the generator emits SQL for a pin-matching artifact", generated.status === 0,
    (generated.stderr || "").trim().slice(0, 200));
  const sqlFile = path.join(releaseDir, "release.sql");
  fs.writeFileSync(sqlFile, generated.stdout || "");
  report("the generated SQL carries no connection string or password",
    !/postgres(ql)?:\/\/|password/i.test(generated.stdout || ""), "credential-shaped text in SQL");

  const applied = psql(["-d", DB, "-f", sqlFile], RUNTIME_ENV);
  report("C1: the publish transaction succeeds as the runtime role", applied.ok,
    applied.out.slice(-300));
  report("C2: the proof line reports the enabled release",
    applied.out.includes(`PROOF: version=${baseEnv.VERSION} latest=true`) &&
    /enabled=true/.test(applied.out) && /artifact=ready/.test(applied.out), applied.out.slice(-300));

  let q = serviceSql("select count(*)::text from public.panel_versions where is_latest");
  report("C3: exactly one latest release", q.ok && q.out === "1", q.out);
  q = serviceSql("select version||' '||enabled::text from public.panel_versions where is_latest");
  report("C4: the latest release is the tracked version, enabled",
    q.ok && q.out === `${baseEnv.VERSION} true`, q.out);
  q = serviceSql("select version from public.panel_versions where minimum_supported");
  report("C5: the minimum supported version matches the tracked policy",
    q.ok && q.out === baseEnv.MINIMUM, q.out);
  const expectedChunks = Math.ceil(artifactBytes.length / CHUNK_BYTES);
  q = serviceSql(`select status||' '||chunk_count::text from public.panel_artifacts where version='${baseEnv.VERSION}'`);
  report("C6: the artifact is finalized with the declared chunk geometry",
    q.ok && q.out === `ready ${expectedChunks}`, q.out);
  q = serviceSql(`select encode(sha256(string_agg(c.data, ''::bytea order by c.chunk_index)), 'hex')
    from public.panel_artifact_chunks c join public.panel_artifacts a on a.id = c.artifact_id
    where a.version='${baseEnv.VERSION}'`);
  report("C7: the reassembled stored bytes equal the artifact digest",
    q.ok && q.out === artifactSha, q.out.slice(0, 80));
  q = serviceSql(`select artifact_id is not null from public.panel_versions where version='${baseEnv.VERSION}'`);
  report("C8: the release row is bound to the finalized artifact", q.ok && q.out === "t", q.out);

  q = serviceSql("select version from public.panel_versions where minimum_supported");
  const gate = evaluatePanelVersion({
    installedVersion: baseEnv.VERSION, minimumSupportedVersion: q.out,
    latestVersion: baseEnv.VERSION, enabled: true,
  });
  const stale = evaluatePanelVersion({
    installedVersion: "6.23.0", minimumSupportedVersion: q.out,
    latestVersion: baseEnv.VERSION, enabled: false,
  });
  report("C9: the server's gate math allows the released version and blocks 6.23.0",
    gate.allowed === true && stale.allowed === false, { gate, stale });

  const reapplied = psql(["-d", DB, "-f", sqlFile], RUNTIME_ENV);
  q = serviceSql("select count(*)::text from public.panel_versions where is_latest");
  report("D1: a second run is a clean no-op that keeps one latest",
    reapplied.ok && q.ok && q.out === "1", reapplied.out.slice(-200));

  /* D3: after the Space mirror, the same generator run records the object
     key on the ALREADY-FINALIZED artifact — exactly how an existing release
     gains its object pointer when the Space comes online later. */
  const objectKey = `ccx/${artifactSha}/${artifactName}`;
  const withObject = runGenerator(Object.assign({}, baseEnv, { OBJECT_KEY: objectKey }));
  fs.writeFileSync(sqlFile, withObject.stdout || "");
  const applied3 = psql(["-d", DB, "-f", sqlFile], RUNTIME_ENV);
  q = serviceSql(`select coalesce(object_key,'') from public.panel_artifacts where version='${baseEnv.VERSION}'`);
  report("D3: the already-finalized artifact gains its Space object pointer",
    withObject.status === 0 && applied3.ok && q.ok && q.out === objectKey &&
    /object=set/.test(applied3.out),
    { gen: withObject.status, genErr: (withObject.stderr || "").slice(0, 200),
      appliedOk: applied3.ok, appliedTail: applied3.out.slice(-700),
      qOk: q.ok, out: q.out.slice(0, 80) });

  const orphanMinimum = runGenerator(Object.assign({}, baseEnv, { MINIMUM: "0.0.1" }));
  fs.writeFileSync(sqlFile, orphanMinimum.stdout || "");
  const aborted = psql(["-d", DB, "-f", sqlFile], RUNTIME_ENV);
  q = serviceSql("select version||' '||enabled::text from public.panel_versions where is_latest");
  report("D2: a minimum without a release record aborts and changes nothing",
    orphanMinimum.status === 0 && !aborted.ok && /RELEASE_ABORT/.test(aborted.out) &&
    q.ok && q.out === `${baseEnv.VERSION} true`, aborted.out.slice(-200));

  cleanup();
  fs.rmSync(releaseDir, { recursive: true, force: true });
  if (failures) { console.error(`\n${failures} contract(s) failed`); process.exit(1); }
  console.log("\nPASS — the panel release lane publishes exactly the tracked artifact, verified");
})();
