/* ============================================================
   HNK Visual Library — the web app's pgLib, in the panel.
   v6.51.0 — this file used to draw its OWN card deck (a title, a subtitle,
   two buttons per card) that the web app never had. The Presets page is now
   the app's Library/Reference page to the pixel: the IMAGE strip, the
   VISUAL LIBRARY card with its search box, the collection and set chips, the
   picked-look panel with "Use as IMAGE 1 / IMAGE 2" and the star, the plate
   grid and its Load-more row. The logic below is the app's Library code
   (docs/app/index.html, pgLib) ported line for line onto UXP's DOM:
   - data is the app's own hnkLibWf JSON (js/hnk_library_compact_data.js,
     generated byte-for-byte, exposed as HNK_LIB_WF);
   - plates come from the licensed web host (ASSET_BASE) — never from Git,
     never from the .ccx — fetched once, kept as data URLs, and painted as
     background-image (UXP has no object-fit);
   - every control is a div the stylesheet owns (UXP's <button> widget draws
     its own chrome and has no Burmese glyphs);
   - main.js publishes HNK.libBridge (language, status line, slot writer);
     this module publishes HNK.lib = { mount, repaint, layout } and the
     HNK.getLibraryPickDataUrl bridge the Smart Workflow inputs use.
   ============================================================ */
(function (global) {
  'use strict';
  var doc = global.document;
  if (!doc) return;

  /* The Library's plate host — pinned by test/verify_panel_gate.js (A5). */
  var ASSET_BASE='https://hnk-ai-tools-3-s4nnu.ondigitalocean.app/app/lib/';

  function $(id) { return doc.getElementById(id); }
  function warn() { try { if (global.console && global.console.warn) global.console.warn.apply(global.console, arguments); } catch (e) { } }
  function bridge() { return (global.HNK && global.HNK.libBridge) || null; }
  function getData() { return global.HNK_LIB_WF || (global.HNK && global.HNK.LIB_WF) || null; }

  /* ---- language: the panel's state.lang via the bridge, the app's L9 rule ---- */
  function lang() {
    var b = bridge();
    try { return (b && b.lang && b.lang()) || 'my'; } catch (e) { return 'my'; }
  }
  function L9(m) {
    var l = lang(), fb = null, b = bridge();
    try { fb = (b && b.fb) ? b.fb(l) : null; } catch (e) { fb = null; }
    return m[l] || (fb && m[fb]) || m.en || m.my || '';
  }
  /* The app's Library copy, in the panel's nine languages. Local to this
     module on purpose — the panel's I18N pack never grows for one page. */
  var LIB_L = {
    refsH2: { my: "ပုံများ (IMAGE 1 = အဓိက Subject)", en: "Images (IMAGE 1 = main subject)", shn: "ၶႅပ်းႁၢင်ႈ (IMAGE 1 = တူဝ်ထိင်)", kac: "Sumla ni (IMAGE 1 = madung)", th: "รูปภาพ (IMAGE 1 = บุคคลหลัก)", zh: "图片（IMAGE 1 = 主体）", vi: "Ảnh (IMAGE 1 = chủ thể chính)", id: "Gambar (IMAGE 1 = subjek utama)", ms: "Imej (IMAGE 1 = subjek utama)" },
    refsNote: { my: "One-Tap တော်တော်များများက IMAGE 1 (ပင်မပုံ) လိုတယ် · Reference သုံးတဲ့ preset တွေက IMAGE 2 ပါ လိုတယ်", en: "Most one-taps need IMAGE 1 (your main photo) · reference presets also need IMAGE 2", shn: "One-Tap ၵမ်ႈၼမ် လူဝ်ႇ IMAGE 1 · preset reference လူဝ်ႇ IMAGE 2 ထႅင်ႈ", kac: "One-Tap law malawng gaw IMAGE 1 ra ai · reference preset ni gaw IMAGE 2 mung ra ai", th: "One-Tap ส่วนใหญ่ต้องมี IMAGE 1 · พรีเซ็ตอ้างอิงต้องมี IMAGE 2 ด้วย", zh: "多数 One-Tap 需要 IMAGE 1 · 参考类预设还需要 IMAGE 2", vi: "Hầu hết One-Tap cần IMAGE 1 · preset tham chiếu cần thêm IMAGE 2", id: "Sebagian besar One-Tap butuh IMAGE 1 · preset referensi juga butuh IMAGE 2", ms: "Kebanyakan One-Tap perlukan IMAGE 1 · preset rujukan perlukan IMAGE 2 juga" },
    searchPh: { my: "ရှာရန် — wedding, child, lighting, myanmar…", en: "Search — wedding, child, lighting, myanmar…", shn: "သွၵ်ႈႁႃ — wedding, child, lighting…", kac: "Tam u — wedding, child, lighting…", th: "ค้นหา — wedding, child, lighting…", zh: "搜索 — wedding、child、lighting…", vi: "Tìm — wedding, child, lighting…", id: "Cari — wedding, child, lighting…", ms: "Cari — wedding, child, lighting…" },
    all: { my: "အားလုံး", en: "All", shn: "တင်းသဵင်ႈ", kac: "Yawng", th: "ทั้งหมด", zh: "全部", vi: "Tất cả", id: "Semua", ms: "Semua" },
    allSets: { my: "အစုံလိုက် အားလုံး", en: "All sets", shn: "ၸုမ်ႇတင်းသဵင်ႈ", kac: "Ahpung yawng", th: "ทุกชุด", zh: "全部系列", vi: "Tất cả bộ", id: "Semua set", ms: "Semua set" },
    more: { my: "နောက်ထပ် ပြရန်", en: "Load more", shn: "ၼႄထႅင်ႈ", kac: "Grau madun", th: "ดูเพิ่ม", zh: "加载更多", vi: "Xem thêm", id: "Muat lagi", ms: "Muat lagi" },
    img1: { my: "IMAGE 1 အဖြစ်", en: "Use as IMAGE 1", shn: "ႁဵတ်း IMAGE 1", kac: "IMAGE 1 hku lang", th: "ใช้เป็น IMAGE 1", zh: "设为 IMAGE 1", vi: "Dùng làm IMAGE 1", id: "Jadikan IMAGE 1", ms: "Jadikan IMAGE 1" },
    img2: { my: "IMAGE 2 အဖြစ် (Reference)", en: "Use as IMAGE 2 (Reference)", shn: "ႁဵတ်း IMAGE 2 (Reference)", kac: "IMAGE 2 (Reference) hku lang", th: "ใช้เป็น IMAGE 2 (อ้างอิง)", zh: "设为 IMAGE 2（参考）", vi: "Dùng làm IMAGE 2 (tham chiếu)", id: "Jadikan IMAGE 2 (Referensi)", ms: "Jadikan IMAGE 2 (Rujukan)" },
    featured: { my: "လက်ရွေးစင်", en: "Featured", shn: "လိူၵ်ႈဝႆႉ", kac: "Lata da ai", th: "แนะนำ", zh: "精选", vi: "Nổi bật", id: "Unggulan", ms: "Pilihan" },
    favs: { my: "ကြိုက်တာများ", en: "My Looks", shn: "ဢၼ်လႆႈၸႂ်", kac: "Ra ai ni", th: "ที่ชอบ", zh: "我的收藏", vi: "Yêu thích", id: "Favorit", ms: "Kegemaran" },
    empty: { my: "ဒီစကားလုံးနဲ့ ဘာမှ မတွေ့ပါ — တခြားစကားလုံးနဲ့ ရှာကြည့်ပါ", en: "No matches for that — try a different search", shn: "ဢမ်ႇႁၼ်သင် — ၸၢမ်းသွၵ်ႈတူၺ်းၶေႃႈၵႂၢမ်းတၢင်ႇဢၼ်", kac: "Hpa n mu ai — ga langai bai tam yu u", th: "ไม่พบผลลัพธ์ — ลองค้นหาคำอื่น", zh: "没有匹配结果 — 试试其他关键词", vi: "Không tìm thấy — hãy thử từ khóa khác", id: "Tidak ada hasil — coba kata kunci lain", ms: "Tiada hasil — cuba kata carian lain" },
    loading: { my: "ယူနေသည်…", en: "Loading…", shn: "တိုၵ်ႉဢဝ်ယူႇ…", kac: "La nga ai…", th: "กำลังโหลด…", zh: "加载中…", vi: "Đang tải…", id: "Memuat…", ms: "Memuatkan…" },
    loadFail: { my: "Library ပုံ မယူနိုင်ပါ — internet စစ်ပါ", en: "Couldn't load this Library image — check your internet", shn: "ဢဝ်ဢမ်ႇလႆႈၶႅပ်းႁၢင်ႈ Library — တွပ်ႇထၢမ် internet", kac: "Library sumla n mai la ai — internet yu chyam u", th: "โหลดรูป Library ไม่ได้ — ตรวจสอบอินเทอร์เน็ต", zh: "无法加载此 Library 图片 — 请检查网络", vi: "Không thể tải ảnh Library này — kiểm tra kết nối internet", id: "Tidak dapat memuat gambar Library ini — periksa internet Anda", ms: "Tidak dapat memuat imej Library ini — semak internet anda" }
  };
  /* Burmese search aliases — the app's HNK_MY_ALIAS, verbatim. */
  var HNK_MY_ALIAS = [["ဆံပင်","hair"],["နောက်ခံ","background"],["မိတ်ကပ်","makeup"],["ဝတ်စုံ","dress outfit gown"],["အလင်း","light lighting relight"],["မျက်နှာ","face"],["မင်္ဂလာ","wedding"],["ပန်း","flower floral"],["သတို့သမီး","bride wedding"],["ကလေး","child baby"],["ဓာတ်ပုံဟောင်း","restore vintage"],["အသားအရေ","skin retouch"],["ရေ","water"],["ကောင်းကင်","sky"],["လိုဂို","logo text"],["ပုံတူ","pose"],["မွေးနေ့","birthday"],["ဘွဲ့","graduation"],["ရိုးရာ","traditional heritage"],["စတူဒီယို","studio"]];

  /* ---- DOM helpers: every control is a div (see verify_panel_gate Q) ---- */
  function el(tag, cls, text) {
    var n = doc.createElement(tag === 'button' ? 'div' : tag);
    if (tag === 'button') { n.setAttribute('role', 'button'); n.setAttribute('tabindex', '0'); }
    if (cls) { n.className = cls; }
    if (text !== undefined) { n.textContent = text; }
    return n;
  }
  function icon(name, tint, cls) {
    var im = doc.createElement('img');
    im.className = cls || 'ic-s';
    im.setAttribute('src', 'icons/ui/' + name + '-' + tint + '.svg');
    im.setAttribute('alt', '');
    return im;
  }
  /* the app's makePickable: click + Enter/Space on a role=button element */
  function pickable(node, fn) {
    node.onclick = fn;
    node.setAttribute('role', 'button');
    node.setAttribute('tabindex', '0');
    node.onkeydown = function (ev) {
      var k = ev && ev.key;
      if (k === 'Enter' || k === ' ' || k === 'Spacebar') { if (ev.preventDefault) ev.preventDefault(); fn(ev); }
    };
  }
  function isOff(btn) { return btn.getAttribute('aria-disabled') === 'true'; }
  function setOff(btn, off) {
    if (off) { btn.setAttribute('aria-disabled', 'true'); btn.classList.add('is-off'); }
    else { btn.removeAttribute('aria-disabled'); btn.classList.remove('is-off'); }
  }
  function toast(msg, kind) {
    var b = bridge();
    try { if (b && b.status) b.status(msg, kind); } catch (e) { warn('lib status:', e); }
  }

  /* ---- plates: fetched once from the licensed host, kept as base64 ---- */
  var B64T = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/';
  function toB64(buf) {
    var b = bridge();
    if (b && b.b64) { try { return b.b64(buf); } catch (e) { } }
    var u = new Uint8Array(buf), out = [], i;
    for (i = 0; i < u.length; i += 3) {
      var a = u[i], c = i + 1 < u.length ? u[i + 1] : 0, d = i + 2 < u.length ? u[i + 2] : 0;
      out.push(B64T[a >> 2], B64T[((a & 3) << 4) | (c >> 4)],
        (i + 1 < u.length) ? B64T[((c & 15) << 2) | (d >> 6)] : '=',
        (i + 2 < u.length) ? B64T[d & 63] : '=');
    }
    return out.join('');
  }
  var plates = {}, plateOrder = [], pending = {}, PLATE_CAP = 400;
  function remember(key, plate) {
    if (!plates[key]) {
      plateOrder.push(key);
      while (plateOrder.length > PLATE_CAP) { var old = plateOrder.shift(); if (old !== key) delete plates[old]; }
    }
    plates[key] = plate;
  }
  function plateUrl(plate) { return 'data:' + plate.mime + ';base64,' + plate.b64; }
  /* tier is "ui" (grid thumbs, 144x180) or "full" (the picked look and the slot) */
  function loadPlate(tier, id) {
    var key = tier + '/' + id;
    if (plates[key]) return Promise.resolve(plates[key]);
    if (pending[key]) return pending[key];
    var p = global.fetch(ASSET_BASE + tier + '/' + id + '.jpg').then(function (r) {
      if (!r || !r.ok) throw new Error('plate ' + key + ' HTTP ' + (r && r.status));
      var ct = '';
      try { ct = (r.headers && r.headers.get && r.headers.get('content-type')) || ''; } catch (e) { ct = ''; }
      return r.arrayBuffer().then(function (buf) {
        if (!buf || !buf.byteLength) throw new Error('plate ' + key + ' empty');
        var mime = /^image\//i.test(ct) ? ct.split(';')[0].trim().toLowerCase() : 'image/jpeg';
        remember(key, { mime: mime, b64: toB64(buf) });
        return plates[key];
      });
    });
    p.then(function () { delete pending[key]; }, function () { delete pending[key]; });
    pending[key] = p;
    return p;
  }
  function paintBg(node, plate) { node.style.backgroundImage = 'url("' + plateUrl(plate) + '")'; }

  /* ---- the app's Library state + logic, verbatim where the DOM allows ---- */
  var lib = { filter: "featured", group: "", search: "", shown: 0, page: 24, list: [], sel: null, selItem: null };
  var favMem = null;
  function libFavList() {
    try { var raw = global.localStorage && global.localStorage.getItem("hnk_ws_lib_favs"); if (raw) return JSON.parse(raw); } catch (e) { }
    return favMem ? favMem.slice() : [];
  }
  function libFavSave(l) {
    favMem = l.slice();
    try { if (global.localStorage) global.localStorage.setItem("hnk_ws_lib_favs", JSON.stringify(l)); } catch (e) { }
  }
  function libInColl(it) {
    if (lib.filter === "favs") return libFavList().indexOf(it.id) >= 0;
    if (lib.filter === "all" || lib.filter === "featured") return true;
    var cs = Array.isArray(it.c) ? it.c : [it.c];
    return cs.indexOf(lib.filter) >= 0;
  }
  function libFiltered() {
    var LW = getData(); if (!LW) return [];
    var q = lib.search.trim().toLowerCase();
    var toks = q ? q.split(/\s+/).filter(Boolean) : [];
    var aliasToks = [];
    if (q) { HNK_MY_ALIAS.forEach(function (pr) { if (q.indexOf(pr[0]) >= 0) aliasToks = aliasToks.concat(pr[1].split(" ")); }); }
    return LW.items.filter(function (it) {
      if (lib.filter === "featured" && LW.featured.indexOf(it.id) < 0 && !q) return false;
      if (!libInColl(it)) return false;
      if (lib.group && it.g !== lib.group) return false;
      if (q) {
        var hit = toks.every(function (tk) { return it.q.indexOf(tk) >= 0; })
          || (aliasToks.length && aliasToks.some(function (tk) { return it.q.indexOf(tk) >= 0; }));
        if (!hit) return false;
      }
      return true;
    });
  }
  /* the app scrolls the active chip into view; UXP's scrollIntoView is
     unproven, so the same result via scrollLeft on the chip strip */
  function revealOn(host) {
    try {
      var onc = host.querySelector('.chip.on'); if (!onc) return;
      var hr = host.getBoundingClientRect(), cr = onc.getBoundingClientRect();
      if (cr.left < hr.left) host.scrollLeft += cr.left - hr.left;
      else if (cr.right > hr.right) host.scrollLeft += cr.right - hr.right;
    } catch (e) { }
  }
  function renderLibFilters() {
    var host = $("libFilters"), LW = getData(); if (!host || !LW) return;
    host.innerHTML = "";
    var opts = [["featured", "i-star-fill", L9(LIB_L.featured)], ["all", L9(LIB_L.all) + " (" + LW.items.length + ")"]];
    var favN = libFavList().length;
    if (favN) opts.push(["favs", "i-star-fill", L9(LIB_L.favs) + " (" + favN + ")"]);
    Object.keys(LW.collections).forEach(function (c) { opts.push([c, c + " (" + LW.collections[c] + ")"]); });
    var featuredBypassed = lib.filter === "featured" && lib.search.trim();
    opts.forEach(function (o) {
      var isOn = lib.filter === o[0] && !(o[0] === "featured" && featuredBypassed);
      var b = el("button", "chip" + (isOn ? " on" : ""));
      if (o.length > 2) { b.appendChild(icon(o[1], isOn ? "ink" : "cream")); b.appendChild(doc.createTextNode(o[2])); }
      else { b.textContent = o[1]; }
      pickable(b, function () { lib.filter = o[0]; lib.group = ""; lib.shown = 0; renderLibFilters(); renderLibGroups(); renderLibGrid(true); });
      host.appendChild(b);
    });
    revealOn(host);
  }
  function renderLibGroups() {
    var host = $("libGroups"), LW = getData(); if (!host || !LW) return;
    host.innerHTML = "";
    if (lib.filter === "featured" && !lib.search.trim()) { host.style.display = "none"; return; }
    var counts = {}, order = [];
    LW.items.forEach(function (it) { if (!it.g || !libInColl(it)) return; if (counts[it.g] === undefined) { counts[it.g] = 0; order.push(it.g); } counts[it.g]++; });
    if (order.length < 2) { host.style.display = "none"; return; }
    host.style.display = "";
    var GO = LW.groupOrder || null; var goIdx = null;
    if (GO && GO.length) { goIdx = {}; for (var gi = 0; gi < GO.length; gi++) goIdx[GO[gi]] = gi; for (var oi = 0; oi < order.length; oi++) if (goIdx[order[oi]] === undefined) { goIdx = null; break; } }
    if (goIdx) order.sort(function (a, b) { return goIdx[a] - goIdx[b]; });
    else order.sort(function (a, b) { return counts[b] - counts[a] || (a < b ? -1 : 1); });
    var opts = [["", L9(LIB_L.allSets)]].concat(order.map(function (g) { return [g, g + " (" + counts[g] + ")"]; }));
    opts.forEach(function (o) {
      var b = el("button", "chip" + (lib.group === o[0] ? " on" : "")); b.textContent = o[1];
      pickable(b, function () { lib.group = o[0]; lib.shown = 0; renderLibGroups(); renderLibGrid(true); });
      host.appendChild(b);
    });
    revealOn(host);
  }
  /* the app's CSS grid (auto-fill, minmax(84px,1fr), 144/180 cells, 6px gap)
     computed by hand — UXP has neither grid nor aspect-ratio */
  var GRID_GAP = 6, GRID_MIN = 84;
  function layout() {
    var host = $("libGrid"); if (!host) return;
    var W = host.clientWidth; if (!W) return;
    var cols = Math.max(1, Math.floor((W + GRID_GAP) / (GRID_MIN + GRID_GAP)));
    var w = Math.floor(((W - (cols - 1) * GRID_GAP) / cols) * 100) / 100;
    var h = Math.floor((w * 180 / 144) * 100) / 100;
    var kids = host.children, n = kids.length, rows = Math.ceil(n / cols);
    for (var i = 0; i < n; i++) {
      var k = kids[i], col = i % cols, row = Math.floor(i / cols);
      k.style.width = w + "px"; k.style.height = h + "px";
      k.style.marginRight = (col === cols - 1 ? 0 : GRID_GAP) + "px";
      k.style.marginBottom = (row === rows - 1 ? 0 : GRID_GAP) + "px";
    }
  }
  var layoutT = null;
  function schedLayout() { if (layoutT) return; layoutT = global.setTimeout(function () { layoutT = null; try { layout(); } catch (e) { } }, 0); }
  function renderLibGrid(reset) {
    var host = $("libGrid"); if (!host) return;
    if (reset) { host.innerHTML = ""; lib.shown = 0; lib.list = libFiltered(); }
    var end = Math.min(lib.list.length, lib.shown + lib.page);
    for (var i = lib.shown; i < end; i++) {
      (function (it) {
        var im = el("div", (lib.sel === it.id ? "sel " : "") + "ld");
        im.title = it.t; im.setAttribute("aria-label", it.t);
        pickable(im, function () { libSelect(it, im); });
        host.appendChild(im);
        loadPlate("ui", it.id).then(function (pl) { paintBg(im, pl); im.classList.remove("ld"); },
          function (e) { im.classList.remove("ld"); warn("lib plate:", e && e.message); });
      })(lib.list[i]);
    }
    lib.shown = end;
    var cnt = $("libCount"); if (cnt) cnt.textContent = end + " / " + lib.list.length;
    var more = $("libMore"); if (more) more.style.display = end < lib.list.length ? "" : "none";
    var empty = $("libEmpty");
    if (empty) {
      empty.classList.toggle("on", !lib.list.length);
      if (!lib.list.length) { var et = $("libEmptyTxt"); if (et) et.textContent = L9(LIB_L.empty); }
    }
    layout();
  }
  function selCell() { var g = $("libGrid"); return g ? g.querySelector(".sel") : null; }
  function libSelect(it, imEl) {
    lib.sel = it.id; lib.selItem = it;
    var g = $("libGrid"), cells = g ? g.children : [];
    for (var i = 0; i < cells.length; i++) cells[i].classList.remove("sel");
    if (imEl) imEl.classList.add("sel");
    var pick = $("libPick"); if (pick) pick.className = "lib-pick on";
    var pim = $("libPickImg");
    if (pim) {
      /* the ui plate is already here — show it now, swap in the full plate when it lands */
      if (plates["ui/" + it.id]) paintBg(pim, plates["ui/" + it.id]); else pim.style.backgroundImage = "";
      loadPlate("full", it.id).then(function (pl) { if (lib.sel === it.id) paintBg(pim, pl); }, function () { });
    }
    var tt = $("libPickTitle"); if (tt) tt.textContent = it.t;
    var sb = $("libPickSub"); if (sb) sb.textContent = (it.tm || it.f || "") + (it.g ? " · " + it.g : "");
    var fv = $("libFav");
    if (fv) { var isFav = libFavList().indexOf(it.id) >= 0; fv.innerHTML = ""; fv.appendChild(icon(isFav ? "i-star-fill" : "i-star", "cream")); fv.setAttribute("aria-pressed", isFav ? "true" : "false"); }
    global.HNK = global.HNK || {};
    global.HNK.lastLibraryPick = { id: it.id, title: it.t };
  }
  function libFavToggle() {
    var it = lib.selItem; if (!it) return;
    var l = libFavList(), i = l.indexOf(it.id);
    if (i >= 0) l.splice(i, 1); else l.unshift(it.id); libFavSave(l);
    if (lib.filter === "favs") { lib.shown = 0; renderLibGrid(true); }
    renderLibFilters(); libSelect(it, selCell());
  }
  function libToSlot(slot, btn) {
    var it = lib.selItem; if (!it) return; if (isOff(btn)) return;
    var origTxt = btn.textContent; setOff(btn, true);
    btn.textContent = L9(LIB_L.loading);
    loadPlate("full", it.id).then(function (pl) {
      var b = bridge(); if (!b || !b.toSlot) throw new Error("no slot bridge");
      if (b.magicOk && !b.magicOk(pl.b64)) throw new Error("plate is not an image");
      b.toSlot(slot, { mime: pl.mime, b64: pl.b64, label: it.t });
      toast("Library · " + it.t + " → IMAGE " + (slot + 1) + " ✓", "ok");
      try {
        var r = $("refs");
        if (r && r.scrollIntoView) r.scrollIntoView({ behavior: "smooth", block: "center" });
        else { var pg = doc.querySelector(".pages"); if (pg) pg.scrollTop = 0; }
      } catch (e) { try { var pg2 = doc.querySelector(".pages"); if (pg2) pg2.scrollTop = 0; } catch (e2) { } }
    }).catch(function (e) { warn("lib to slot:", e && e.message); toast(L9(LIB_L.loadFail), "err"); })
      .then(function () { setOff(btn, false); btn.textContent = origTxt; });
  }
  function targetSlot(dflt) {
    var b = bridge(), s = null;
    try { if (b && b.takeTargetSlot) s = b.takeTargetSlot(); } catch (e) { s = null; }
    return (typeof s === "number") ? s : dflt;
  }

  /* ---- static copy (repainted on every language switch) ---- */
  function paintStatic() {
    var LW = getData();
    var h2 = $("refsH2"); if (h2) h2.textContent = L9(LIB_L.refsH2);
    var nt = $("refsNote"); if (nt) nt.textContent = L9(LIB_L.refsNote);
    var si = $("libSearch"); if (si) si.setAttribute("placeholder", L9(LIB_L.searchPh));
    var b1 = $("libToImg1"); if (b1 && !isOff(b1)) b1.textContent = L9(LIB_L.img1);
    var b2 = $("libToImg2"); if (b2 && !isOff(b2)) b2.textContent = L9(LIB_L.img2);
    var mr = $("libMore"); if (mr) mr.textContent = L9(LIB_L.more);
    var tot = $("libTotal"); if (tot && LW) tot.textContent = LW.items.length;
    var et = $("libEmptyTxt"); if (et && lib.list && !lib.list.length) et.textContent = L9(LIB_L.empty);
  }

  var mounted = false, _libT = null;
  function mount() {
    if (mounted) return true;
    var grid = $("libGrid"), LW = getData();
    if (!grid || !LW) return false;
    mounted = true;
    try {
      var fv = $("libFav"); if (fv) pickable(fv, libFavToggle);
      var b1 = $("libToImg1"); if (b1) pickable(b1, function () { libToSlot(targetSlot(0), b1); });
      var b2 = $("libToImg2"); if (b2) pickable(b2, function () { libToSlot(targetSlot(1), b2); });
      var si = $("libSearch");
      if (si) si.addEventListener("input", function () {
        var v = si.value; global.clearTimeout(_libT);
        if (v === "") { lib.search = ""; renderLibFilters(); renderLibGroups(); renderLibGrid(true); return; }
        _libT = global.setTimeout(function () { lib.search = v; renderLibFilters(); renderLibGroups(); renderLibGrid(true); }, 120);
      });
      var more = $("libMore"); if (more) pickable(more, function () { renderLibGrid(false); });
      paintStatic();
      renderLibFilters(); renderLibGroups(); renderLibGrid(true);
      global.addEventListener("resize", schedLayout);
    } catch (e) { warn("lib mount:", e); }
    return true;
  }
  function repaint() {
    if (!mount()) return;
    try {
      paintStatic();
      renderLibFilters(); renderLibGroups();
      if (lib.selItem) libSelect(lib.selItem, selCell());
      layout();
    } catch (e) { warn("lib repaint:", e); }
  }

  /* ---- public surface ---- */
  var H = global.HNK = global.HNK || {};
  H.lib = { mount: mount, repaint: repaint, layout: function () { try { layout(); } catch (e) { } }, state: lib };
  /* Library → Smart Workflow bridge: the last-picked look as a data URL
     (null when nothing has been picked yet). */
  H.getLibraryPickDataUrl = function () {
    var p = H.lastLibraryPick;
    if (!p || !p.id) return Promise.resolve(null);
    return loadPlate("full", p.id).then(function (pl) { return { dataUrl: plateUrl(pl), title: p.title || "" }; });
  };

  function auto() { try { mount(); } catch (e) { warn("lib auto-mount:", e); } }
  if (doc.readyState === 'loading') { doc.addEventListener('DOMContentLoaded', auto); } else { global.setTimeout(auto, 0); }
})(typeof globalThis !== 'undefined' ? globalThis : window);
