/* ============================================================
   HNK "what's new" list — LIFTED, do not edit by hand.
   Source of truth: the web app's own WHATS_NEW table
   (docs/app/index.html), copied verbatim so a student is told the
   same thing in Photoshop as on their phone, in the same words and
   the same nine languages. test/verify_panel_whats_new.js pins this
   file to the app's, entry for entry.
   ============================================================ */
(function () {
"use strict";
var WHATS_NEW = [
  { v:"5.99.0", kind:"wf", ref:"derma-skin",
    t:{my:"Derma Skin Pro ရဲ့ ခလုတ်တွေ ပြောတဲ့အတိုင်း အလုပ်လုပ်ပါပြီ",en:"Derma Skin Pro's switches now mean what they say",shn:"ၼဵၼ် Derma Skin Pro ႁဵတ်းမိူၼ်ဢၼ်ဝႃႈ",kac:"Derma Skin Pro switch ni tsun ai hte maren galaw sai",th:"สวิตช์ของ Derma Skin Pro ทำงานตรงตามที่บอกแล้ว",zh:"Derma Skin Pro 的开关现在名副其实",vi:"Các công tắc của Derma Skin Pro giờ đúng như tên gọi",id:"Sakelar Derma Skin Pro kini sesuai dengan namanya",ms:"Suis Derma Skin Pro kini menepati namanya"},
    s:{my:"ခလုတ် ၅ ခုလုံးမှာ ပိတ်ရင် ဘာဖြစ်မလဲ ပြောတဲ့ စာကြောင်း မပါခဲ့ဘူး — အမာရွတ်ဖျောက်ခြင်း ပိတ်ထားရင်တောင် prompt က အသားအရေ ရှင်းနေဖို့ ဆက်တောင်းနေခဲ့တယ်။ ကိုယ်လုံး ပိတ်ရင်လည်း ကိုယ်လုံးကို ဆက်ပြင်နေခဲ့တယ်။ မှဲ့ကိစ္စမှာလည်း prompt နဲ့ AVOID စာရင်း အချင်းချင်း ဆန့်ကျင်နေခဲ့တယ် — ၃ ခုလုံး ပြင်ပြီးပါပြီ",en:"None of the five switches said what OFF meant, so turning blemish healing off still left the request demanding clear skin, and turning body skin off still had the healing line reaching the body. The AVOID list also forbade the mole removal the prompt asked for — all three are fixed",shn:"ၼဵၼ် 5 ဢၼ် ဢမ်ႇမီးၶေႃႈဝႃႈပိၵ်ႉသေပဵၼ်သင် — ယၢမ်းလဵဝ် မႄးယဝ်ႉ",kac:"Switch 5 hta pat yang hpa byin na n tsun ai — ya gaw mai sai",th:"สวิตช์ทั้ง 5 ไม่เคยบอกว่าปิดแล้วเกิดอะไร ปิดลบสิวแล้วคำสั่งยังเรียกร้องผิวใส และปิดผิวกายแล้วยังลบสิวที่ลำตัว รวมถึงรายการ AVOID ที่ห้ามลบไฝซึ่งพรอมต์สั่งให้ลบ — แก้ครบทั้งสามแล้ว",zh:"五个开关都没有说明关闭后会怎样：关掉祛瑕疵，请求仍在要求无瑕肌肤；关掉身体皮肤，祛瑕疵那行仍会处理身体。AVOID 列表还禁止了提示词要求的去痣 — 三处已全部修好",vi:"Cả năm công tắc đều không nói TẮT nghĩa là gì: tắt xoá khuyết điểm mà yêu cầu vẫn đòi da sạch, tắt da cơ thể mà dòng xoá khuyết điểm vẫn chạm tới thân. Danh sách AVOID còn cấm việc xoá nốt ruồi mà prompt yêu cầu — cả ba đã sửa",id:"Kelima sakelar tak menjelaskan arti MATI: mematikan penghapus noda tetap menyisakan permintaan kulit bersih, dan mematikan kulit tubuh tetap membuat baris penghapus noda menjangkau tubuh. Daftar AVOID juga melarang penghapusan tahi lalat yang diminta prompt — ketiganya sudah diperbaiki",ms:"Kelima-lima suis tidak menyatakan maksud MATI: mematikan penghapus cela masih meninggalkan permintaan kulit bersih, dan mematikan kulit badan masih membuatkan baris penghapus cela mencapai badan. Senarai AVOID turut melarang pembuangan tahi lalat yang diminta gesaan — ketiga-tiganya telah dibaiki"} },
  { v:"5.98.0", kind:"wf", ref:"look-highland-indigo",
    t:{my:"ပိုစ့်နဲ့ ဓာတ်ပုံအကွက် မူရင်းအတိုင်း ကျန်ပါပြီ",en:"Your pose and your framing now stay exactly as you shot them",shn:"ၽၢင်ႁၢင်ႈလႄႈ ၶွပ်ႇၶႅပ်း ၵိုတ်းမိူၼ်ၵဝ်ႇ",kac:"Na a pose hte frame gaw shawng na zawn nga na",th:"ท่าโพสและกรอบภาพคงเดิมตามที่ถ่ายแล้ว",zh:"你的姿势与构图现在会原样保留",vi:"Dáng và khuôn hình của bạn nay giữ nguyên như lúc chụp",id:"Pose dan komposisimu kini tetap persis seperti saat difoto",ms:"Pose dan komposisi anda kini kekal seperti ketika dirakam"},
    s:{my:"Look Set ၁၃ ခုလုံးမှာ “ပိုစ့်ကတော့ ပြောင်းတယ်” လို့ ဖတ်လို့ရတဲ့ စာကြောင်းတစ်ကြောင်း ပါနေခဲ့ပြီး အောက်က စည်းကမ်းနဲ့ ကိုယ်တိုင် ဆန့်ကျင်နေတာ — ဖြုတ်လိုက်ပြီး pose၊ camera angle၊ crop၊ frame ratio တွေကို prompt အစမှာကတည်းက သော့ခတ်လိုက်ပါပြီ",en:"All thirteen sets carried one sentence a model could read as “the pose does change”, three lines above a rule saying it must not — it is gone, and pose, camera angle, crop and aspect ratio are now locked in the prompt's opening line",shn:"Look Set 13 ဢၼ်မီးဝႆႉၶေႃႈၼိုင်ႈ ၶတ်းၵၼ်တင်းမၢႆမီႈတႂ်ႈ — ထွၼ်ဢွၵ်ႇယဝ်ႉ",kac:"Look Set 13 ting hta tsun ga langai npawt hte shada n hkrum ai nga ai — shaw kau sai",th:"ทั้ง 13 เซ็ตเคยมีประโยคที่โมเดลอ่านได้ว่า “ท่าเปลี่ยนได้” ซึ่งขัดกับกฎด้านล่าง — ตอนนี้ลบออกแล้ว และล็อกท่า มุมกล้อง การครอป และอัตราส่วนไว้ตั้งแต่บรรทัดแรก",zh:"十三组套装都带着一句可被读成「姿势是会变的」的话，而三行之下的规则却说不可以 — 这句已删除，姿势、机位、裁切与画面比例改在提示词第一行就锁定",vi:"Cả mười ba bộ đều mang một câu có thể bị đọc thành “dáng thì có đổi”, ngay trên quy tắc nói không được — câu đó đã bỏ, và dáng, góc máy, khung cắt, tỷ lệ nay khoá ngay dòng đầu",id:"Ketiga belas set memuat satu kalimat yang bisa dibaca sebagai “pose memang berubah”, tepat di atas aturan yang melarangnya — kalimat itu dihapus, dan pose, sudut kamera, krop serta rasio kini dikunci di baris pertama",ms:"Kesemua tiga belas set membawa satu ayat yang boleh dibaca sebagai “pose memang berubah”, tepat di atas peraturan yang melarangnya — ayat itu dibuang, dan pose, sudut kamera, kropan serta nisbah kini dikunci pada baris pertama"} },
  { v:"5.98.0", kind:"page", ref:"pgCreate",
    t:{my:"Ratio = Auto ဆိုရင် ကိုယ့်ပုံရဲ့ ပုံသဏ္ဌာန်အတိုင်း ထွက်ပါပြီ",en:"Ratio on Auto now means the shape your photo already is",shn:"Ratio Auto ၸိုင် ပဵၼ်ႁၢင်ႈၶႅပ်းႁၢင်ႈၸဝ်ႈၵဝ်ႇ",kac:"Ratio Auto gaw na a sumla a hkum hte maren",th:"Ratio = Auto ตอนนี้หมายถึงสัดส่วนเดิมของภาพคุณ",zh:"比例设为 Auto，现在就是你照片本来的形状",vi:"Ratio để Auto giờ chính là hình dạng vốn có của ảnh bạn",id:"Ratio pada Auto kini berarti bentuk asli fotomu",ms:"Nisbah pada Auto kini bermaksud bentuk asal foto anda"},
    s:{my:"model ၆ ခုမှာ Auto က တကယ်တော့ 1:1 (စတုရန်း) ပို့နေခဲ့တာ — ဒါကြောင့် prompt က ဘာပဲပြောပြော ဓာတ်ပုံက စတုရန်း ပြန်လာတာ။ အခု မူရင်းပုံကို တိုင်းပြီး အနီးစပ်ဆုံး ratio ကို ပို့ပါတယ်",en:"On six models Auto was really sending 1:1 — square — so a portrait came back square no matter what the prompt said. Your photo is now measured and the nearest supported ratio is sent instead",shn:"model 6 ဢၼ် Auto သူင်ႇ 1:1 — ယၢမ်းလဵဝ် တႅၵ်ႈၶႅပ်းႁၢင်ႈသေ သူင်ႇဢၼ်ႁဵတ်းၸမ်",kac:"Model 6 hta Auto gaw 1:1 sa ai — ya gaw sumla hpe shadawn nna ni htum ai ratio sa na",th:"บนโมเดล 6 ตัว Auto ส่งเป็น 1:1 (จัตุรัส) จริง ๆ ภาพจึงกลับมาเป็นจัตุรัสไม่ว่าพรอมต์จะบอกอะไร ตอนนี้วัดจากภาพต้นฉบับแล้วส่งอัตราส่วนที่ใกล้ที่สุด",zh:"在六个模型上，Auto 实际发送的是 1:1 正方形，所以无论提示词怎么写，人像都会变成方图。现在会测量你的原图并发送最接近的受支持比例",vi:"Trên sáu model, Auto thực chất gửi 1:1 — vuông — nên ảnh chân dung trả về hình vuông dù prompt viết gì. Nay ảnh của bạn được đo và gửi tỷ lệ gần nhất được hỗ trợ",id:"Pada enam model, Auto sebenarnya mengirim 1:1 — persegi — sehingga potret kembali persegi apa pun isi prompt. Kini fotomu diukur dan rasio terdekat yang didukung dikirim",ms:"Pada enam model, Auto sebenarnya menghantar 1:1 — segi empat sama — jadi potret kembali sebagai segi empat walau apa pun gesaannya. Kini foto anda diukur dan nisbah disokong yang terdekat dihantar"} },
  { v:"5.97.0", kind:"wf", ref:"look-golden-grecian",
    t:{my:"Look Set တွေမှာ အဖြူရောင် မီးလုံးကြီး မပါတော့ပါ",en:"The white light blob is gone from the Look Sets",shn:"ၼႂ်း Look Set ဢမ်ႇမီး လွင်ႈလႅင်းၽိူၵ်ႇလူင်ယဝ်ႉ",kac:"Look Set ni hta nsam hpraw kaba nlu mat sai",th:"ดวงแสงขาวใหญ่หายไปจากเซ็ตลุคแล้ว",zh:"造型套装里的大白光斑没有了",vi:"Vệt sáng trắng lớn đã biến khỏi các Look Set",id:"Bercak cahaya putih besar hilang dari Look Set",ms:"Tompok cahaya putih besar hilang daripada Look Set"},
    s:{my:"ဓာတ်ပုံထောင့်မှာ ဝင်လာတတ်တဲ့ အလင်းဖြူပွင့်ကြီးကို ၁၃ ခုလုံးမှာ ပိတ်လိုက်ပါပြီ — မီးအိမ်၊ softbox၊ flare မပေါ်တော့ဘဲ အလင်းအဆုံးနေရာမှာလည်း အသေးစိတ် ကျန်ပါတယ်",en:"A blown white glow used to bleed into the corner of the frame — all thirteen sets now forbid it, so no lamp, softbox or flare shows and even the brightest area keeps its detail",shn:"လႅင်းၽိူၵ်ႇလူင် ဢၼ်ၶဝ်ႈမႃးတီႈၸဵင်ႇ ၶႅပ်းႁၢင်ႈ — ယၢမ်းလဵဝ် ႁၢမ်ႈဝႆႉတင်း 13 ၸုမ်း",kac:"Sumla n-gang de nsam hpraw shang wa ai hpe ya gaw 13 ting hta n hkap la sai",th:"แสงขาวจ้าที่เคยเลียเข้ามาที่มุมภาพ ถูกห้ามในทั้ง 13 เซ็ตแล้ว ไม่มีโคมไฟ ซอฟต์บ็อกซ์ หรือแฟลร์ และส่วนที่สว่างที่สุดยังคงรายละเอียด",zh:"过去会从画面角落渗入的死白光晕，现在十三组套装全部禁止 — 不再出现灯具、柔光箱或炫光，最亮处也保留细节",vi:"Vệt sáng trắng cháy từng loang vào góc khung hình — cả mười ba bộ nay đều cấm, không lộ đèn, softbox hay flare và vùng sáng nhất vẫn giữ chi tiết",id:"Cahaya putih menyilaukan yang dulu merembes ke sudut bingkai kini dilarang di ketiga belas set — tak ada lampu, softbox atau flare, dan area paling terang tetap berdetail",ms:"Cahaya putih terlebih dedah yang dahulu meresap ke sudut bingkai kini dilarang pada kesemua tiga belas set — tiada lampu, softbox atau suar, dan kawasan paling cerah kekal berbutir"} },
  { v:"5.97.0", kind:"page", ref:"pgPath",
    t:{my:"တစ်စီးရီးလုံး engine တစ်ခုတည်းကနေ ထွက်ပါပြီ",en:"One series now comes out of one engine",shn:"ၸုတ်းလဵဝ် ဢွၵ်ႇမႃးတီႈ engine လဵဝ်",kac:"Series langai gaw engine langai kaw na pru wa sai",th:"หนึ่งชุดภาพออกมาจากเอนจินเดียว",zh:"一整组照片现在出自同一个引擎",vi:"Một loạt ảnh giờ ra từ cùng một engine",id:"Satu seri kini keluar dari satu engine",ms:"Satu siri kini terhasil daripada satu enjin"},
    s:{my:"ဓာတ်ပုံ ၁၀၀ လုပ်နေရင်း model ပြောင်းသွားရင် အသွင်အပြင် မတူတော့ဘူး — အခု စတင်ချိန်က model ကို အဆုံးထိ ကိုင်ထားပြီး တစ်ခုခု တခြား engine ကနေ ထွက်ခဲ့ရင်လည်း အစီရင်ခံပါတယ်",en:"A model swapped halfway through a hundred photos used to leave them looking unalike — the run now holds the model it started with, and reports it if anything still came from another",shn:"ႁဵတ်းၶႅပ်းႁၢင်ႈ 100 သေ လႅၵ်ႈ model ၵၢင်တၢင်း ၸိုင် ဢမ်ႇမိူၼ်ၵၼ် — ယၢမ်းလဵဝ် ၵမ် model ဢွၼ်တၢင်းဝႆႉတေႃႇသုတ်း",kac:"Sumla 100 galaw nga yang ka-ang hta model galai ai majaw n bung mat ai — ya gaw nnan hpang ai model hpe hpang jahtum du hkra jum da na",th:"การเปลี่ยนโมเดลกลางคันระหว่างทำ 100 ภาพเคยทำให้ภาพไม่เข้ากัน — ตอนนี้จะยึดโมเดลที่เริ่มไว้จนจบ และรายงานถ้ามีภาพใดมาจากเอนจินอื่น",zh:"一百张照片做到一半换了模型，成片就不像同一组 — 现在整轮固定使用开始时的模型，若仍有出自其他引擎的也会如实报告",vi:"Đổi model giữa chừng khi làm một trăm ảnh từng khiến chúng không giống nhau — nay cả lượt giữ nguyên model lúc bắt đầu, và báo lại nếu vẫn có ảnh đến từ engine khác",id:"Model yang berganti di tengah seratus foto dulu membuat hasilnya tak senada — kini satu putaran memegang model saat dimulai, dan melaporkannya bila ada yang tetap dari engine lain",ms:"Model yang bertukar di pertengahan seratus foto dahulu menjadikan hasilnya tidak sepadan — kini satu pusingan mengekalkan model ketika dimulakan, dan melaporkannya jika ada yang masih daripada enjin lain"} },
  { v:"5.96.0", kind:"wf", ref:"look-temple-lightfall",
    t:{my:"Look Set တွေ ပိုတိုပြီး ပိုပြည့်စုံလာပါပြီ",en:"The Look Sets got shorter, and arrive more complete",shn:"Look Set ပွင်ႇထႅမ်လိူဝ်သေ ပွတ်းလိူဝ်",kac:"Look Set ni kadun nna grau hkum wa sai",th:"เซ็ตลุคสั้นลงและส่งถึงครบขึ้น",zh:"造型套装更短了，也更完整地送达",vi:"Các Look Set ngắn hơn và đến nơi đầy đủ hơn",id:"Look Set jadi lebih ringkas dan sampai lebih utuh",ms:"Look Set menjadi lebih ringkas dan sampai lebih lengkap"},
    s:{my:"prompt ရဲ့ ၆၂% က ၁၃ ခုလုံးမှာ ထပ်နေတဲ့ စာသားပါ — အဓိပ္ပာယ် မလျော့ဘဲ စာလုံး ၉၀၀ လျှော့လိုက်လို့ model ပိုများများမှာ set အပြည့် ရောက်ပါပြီ",en:"62% of each prompt was text repeated in all thirteen — 900 characters lighter with nothing dropped, so more models now receive the whole set",shn:"prompt 62% ပဵၼ်ၶေႃႈထပ်း — မွၵ်ႈ 900 တူဝ်ဢေႇလူင်း",kac:"Prompt 62% gaw bai tsun ai re — 900 chars kadun sai",th:"62% ของพรอมต์เป็นข้อความซ้ำ — เบาลง 900 ตัวอักษรโดยไม่เสียความหมาย",zh:"每条提示词有 62% 是十三组共用的重复文字 — 精简 900 字符而不丢失任何规则",vi:"62% mỗi prompt là chữ lặp lại ở cả mười ba — nhẹ đi 900 ký tự mà không mất quy tắc nào",id:"62% tiap prompt adalah teks berulang di ketiga belasnya — 900 karakter lebih ringan tanpa kehilangan aturan",ms:"62% setiap gesaan ialah teks berulang pada kesemua tiga belas — 900 aksara lebih ringan tanpa kehilangan sebarang peraturan"} },
  { v:"5.95.0", kind:"page", ref:"pgWf",
    t:{my:"Model ပြောင်းရင် prompt အလိုအလျောက် လိုက်ညှိပါပြီ",en:"The prompt now fits itself to the model you pick",shn:"လႅၵ်ႈ model ၸိုင် prompt ငၢႆႈငၢႆႈလိုၵ်ႉ",kac:"Model galai yang prompt hkrak hkra galai sai",th:"พรอมต์ปรับตามโมเดลที่เลือกอัตโนมัติแล้ว",zh:"提示词现在会自动适配你选的模型",vi:"Prompt giờ tự khớp với model bạn chọn",id:"Prompt kini menyesuaikan diri dengan model yang dipilih",ms:"Gesaan kini menyesuaikan diri dengan model yang dipilih"},
    s:{my:"prompt ရှည်ရင် စာကြောင်းအလယ် ဖြတ်တာမျိုး မလုပ်တော့ဘဲ မလိုအပ်တဲ့ အပိုင်းလိုက် ဖြုတ်ပါတယ် — မဝင်နိုင်ရင်တော့ အပြည့်လက်ခံနိုင်တဲ့ model ဆီ ပြောင်းပြီး ဘာကြောင့်လဲ ပြောပြပါတယ်",en:"A long workflow now loses whole sections it can spare instead of stopping mid-sentence — and when even that won't fit, the run moves to a model that can take all of it, and says why",shn:"prompt ယၢဝ်း ၸိုင် တတ်ႉၵၢင်ဝႃႇၵျႃႇဢမ်ႇမီး — ဢမ်ႇမႅၼ်ႈၸိုင် လႅၵ်ႈ model",kac:"Prompt galu yang ka-ang hta n kadun sai — n hkrak yang model galai na",th:"เวิร์กโฟลว์ยาวจะตัดทั้งส่วนแทนการตัดกลางประโยค — ถ้ายังไม่พอจะย้ายไปโมเดลที่รับได้ทั้งหมด",zh:"较长的工作流现在整段舍弃而不是从句子中间截断 — 若仍放不下，会切换到能完整接受的模型",vi:"Workflow dài giờ bỏ trọn từng phần thay vì cắt giữa câu — nếu vẫn không vừa, sẽ chuyển sang model nhận được toàn bộ",id:"Alur panjang kini melepas bagian utuh alih-alih terpotong di tengah kalimat — bila masih tak muat, dipindah ke model yang bisa menerima seluruhnya",ms:"Aliran panjang kini melepaskan bahagian penuh dan bukan terpotong di tengah ayat — jika masih tidak muat, ia bertukar ke model yang boleh menerima kesemuanya"} },
  { v:"5.94.0", kind:"page", ref:"pgCreate",
    t:{my:"ရွေးလိုက်တဲ့ ratio နဲ့ size အမှန်ထွက်ပါပြီ",en:"The ratio and size you pick now really come out",shn:"ratio လႄႈ size ဢၼ်လိူၵ်ႈ ဢွၵ်ႇမႃးတႄႉယဝ်ႉ",kac:"Lata ai ratio hte size teng sha pru wa sai",th:"อัตราส่วนและขนาดที่เลือกออกมาจริงแล้ว",zh:"你选择的比例和尺寸现在真的会生效",vi:"Tỷ lệ và kích thước bạn chọn giờ thực sự ra đúng",id:"Rasio dan ukuran yang kamu pilih kini benar-benar diterapkan",ms:"Nisbah dan saiz yang anda pilih kini benar-benar digunakan"},
    s:{my:"Seedream v4/v4.5 မှာ ratio ရွေးလို့ရပေမဲ့ တကယ်မပါခဲ့ဘူး — အခု မလိုတဲ့ခလုတ်ကို ဖျောက်ထားပါပြီ။ Size က ratio ပေါ်မူတည်တဲ့ model တွေမှာလည်း ကြိုပြောပါပြီ",en:"Seedream v4/v4.5 let you pick a ratio that was never sent — that control is now hidden. And where size comes from the ratio, the app says so before you spend a credit",shn:"Seedream v4/v4.5 လိူၵ်ႈ ratio လႆႈသေတႃႉ ဢမ်ႇသူင်ႇ — ယၢမ်းလဵဝ် ဢိုတ်းဝႆႉ",kac:"Seedream v4/v4.5 hta ratio lata mai tim n sa ai — ya gaw makoi da sai",th:"Seedream v4/v4.5 เคยให้เลือกอัตราส่วนที่ไม่เคยถูกส่ง — ตอนนี้ซ่อนแล้ว",zh:"Seedream v4/v4.5 曾允许选择从未被发送的比例 — 该控件现已隐藏",vi:"Seedream v4/v4.5 từng cho chọn tỷ lệ không bao giờ được gửi — nay đã ẩn",id:"Seedream v4/v4.5 dulu membiarkan memilih rasio yang tak pernah dikirim — kini disembunyikan",ms:"Seedream v4/v4.5 dahulu membenarkan pilihan nisbah yang tidak pernah dihantar — kini disembunyikan"} },
  { v:"5.93.0", kind:"page", ref:"pgHome",
    t:{my:"ဝင်လို့မရရင် ဘာကြောင့်လဲ ရှင်းရှင်းပြောပါပြီ",en:"When sign-in fails, it now tells you why",shn:"ၶဝ်ႈဢမ်ႇလႆႈၸိုင် ၸႅင်ႈလႅင်းဝႃႈသင်",kac:"Shang n mai yang hpa majaw re tsun sai",th:"ถ้าเข้าสู่ระบบไม่ได้ ตอนนี้บอกสาเหตุแล้ว",zh:"登录失败时，现在会说明原因",vi:"Khi đăng nhập lỗi, giờ sẽ nói rõ vì sao",id:"Saat gagal masuk, kini dijelaskan sebabnya",ms:"Apabila log masuk gagal, kini ia menyatakan sebabnya"},
    s:{my:"ခဏစောင့်ရမလား၊ စကားဝှက် မှားနေလား၊ အင်တာနက် ပြဿနာလား — အခု ခွဲပြီး ပြောပါတယ်။ ကီးဘုတ်က Go ခလုတ်နဲ့လည်း ဝင်လို့ရပါပြီ",en:"Whether to wait, fix your password, or check your connection — the app now says which. And the keyboard's Go key signs you in",shn:"ပႂ်ႉၼႃႇ၊ ၶေႃႈလပ်ႉၽိတ်း၊ ဢိၼ်ႇတိူဝ်ႇၼႅတ်ႉ — ၸႅင်ႈလႅင်းယဝ်ႉ။ ၼဵၼ် Go ၵေႃႈၶဝ်ႈလႆႈ",kac:"La ra na, password shut ai, sh'ning internet — ya tsun dan sai. Keyboard Go mung shang mai sai",th:"ต้องรอ ต้องแก้รหัสผ่าน หรือปัญหาเน็ต — ตอนนี้บอกชัด และปุ่ม Go บนคีย์บอร์ดก็เข้าสู่ระบบได้",zh:"是要等待、密码错误，还是网络问题 — 现在会分清楚。键盘上的 Go 键也能登录",vi:"Cần đợi, sai mật khẩu, hay lỗi mạng — giờ ứng dụng nói rõ. Phím Go trên bàn phím cũng đăng nhập được",id:"Harus menunggu, kata sandi salah, atau masalah koneksi — kini dijelaskan. Tombol Go di keyboard juga bisa masuk",ms:"Perlu menunggu, kata laluan salah, atau masalah sambungan — kini dinyatakan. Kekunci Go pada papan kekunci juga boleh log masuk"} },
  /* v5.92.0 points at the Workflows page, not at a Look Set card: the news
     is a change to every set's switches, so the shelf is the honest
     destination. (It was once also a workaround — two unread entries could
     not both lead one category. Since 5.97.0 they can: the render sorts
     every unread card forward and verify_whats_new E2 checks the whole
     leading run, so an entry may now name whatever it actually changed.) */
  { v:"5.92.0", kind:"page", ref:"pgWf",
    t:{my:"ခလုတ်ပိတ်ရင် ဘာဖြစ်မလဲ ရှင်းပါပြီ",en:"Every switch now says what OFF means",shn:"ပိၵ်ႉသေ ပဵၼ်သင် ၸႅင်ႈလႅင်းယဝ်ႉ",kac:"Switch pat yang hpa byin na chye sai",th:"ปิดสวิตช์แล้วเกิดอะไร ชัดเจนแล้ว",zh:"每个开关都说明了关闭时的效果",vi:"Mỗi công tắc giờ nói rõ TẮT nghĩa là gì",id:"Setiap sakelar kini menjelaskan arti MATI",ms:"Setiap suis kini menyatakan maksud MATI"},
    s:{my:"Look Set မှာ ဝတ်စုံ+မိတ်ကပ် ပိတ်ရင် ကိုယ့်အဝတ်အစား အတိအကျ ကျန်မယ် — prompt ရှည်ရင်လည်း model တိုင်းက အလုပ်အဓိကကို အရင်ရပါပြီ",en:"Turn Wardrobe+makeup off on a Look Set and your own outfit stays exactly as shot — and on models that cut long prompts, the task now arrives first",shn:"ပိၵ်ႉၶူဝ်းၼုင်ႈ+မဵၵ်ႉၶၢပ်ႈ ၼႂ်း Look Set သေ ၶူဝ်းၼုင်ႈတူဝ်ၵဝ်ႇ ၵိုတ်းဝႆႉမိူၼ်ၵဝ်ႇ — model ဢၼ်တတ်ႉ prompt ၵေႃႈ လႆႈၵၢၼ်ၼႃႈဢွၼ်တၢင်း",kac:"Look Set hta Palawng+makeup pat yang na palawng nan hte raw nga na — prompt kadun ai model ni mung bungli hpe shawng la na",th:"ปิดชุดและแต่งหน้าใน Look Set แล้วชุดของคุณจะคงเดิมทุกอย่าง — และโมเดลที่ตัด prompt ยาวจะได้รับงานหลักก่อน",zh:"在造型套装中关闭服装与妆容，你自己的穿着将原样保留 — 会截断长提示词的模型现在也会先收到任务本身",vi:"Tắt Trang phục+trang điểm trong Look Set thì trang phục của bạn giữ nguyên như ảnh chụp — và các model cắt prompt dài giờ nhận phần việc chính trước",id:"Matikan Busana+riasan di Look Set dan pakaianmu tetap persis seperti difoto — dan model yang memotong prompt panjang kini menerima tugas utamanya lebih dulu",ms:"Matikan Busana+solekan dalam Look Set dan pakaian anda kekal seperti difoto — dan model yang memotong prompt panjang kini menerima tugas utama dahulu"} },
  { v:"5.91.0", kind:"wf", ref:"look-golden-grecian",
    t:{my:"Look Set ကတ်အသစ် ၁၃ ခု",en:"Thirteen new Look Sets",shn:"ၸုမ်းလင်ႇသဵၼ်ႈမႂ်ႇ 13",kac:"Look Set nnan 13",th:"13 เซ็ตลุคใหม่",zh:"13 组全新造型套装",vi:"13 bộ Look Set mới",id:"13 Look Set baru",ms:"13 Look Set baharu"},
    s:{my:"နောက်ခံအရောင်၊ အလင်း၊ အရောင်ချိန်၊ ဝတ်စုံ အတိအကျ တစ်ပုံစံတည်း — ပုံ ၁၀၀ လုပ်လည်း တစ်ရိုက်တည်းလို။ ဝတ်စုံ+မိတ်ကပ် နဲ့ အသားရောင် ခလုတ် သီးသန့်ပါတယ်",en:"Backdrop, light, grade and wardrobe fixed on every photo, so a hundred frames read as one shoot — with their own wardrobe+makeup and skin-tone switches",shn:"သီလင်၊ ၾႆး၊ လၢႆးသီ၊ ၶူဝ်းၼုင်ႈ မိူၼ်ၵၼ်ၵူႊၶႅပ်း",kac:"Shakum, nhtoi, grade, palawng yawng maren",th:"ฉาก แสง เกรดสี และชุด เหมือนกันทุกภาพ",zh:"背景、布光、调色与服装每张一致",vi:"Phông, ánh sáng, màu và trang phục giống nhau mọi ảnh",id:"Latar, cahaya, grading dan busana sama di setiap foto",ms:"Latar, cahaya, gred dan busana sama pada setiap foto"} },
  { v:"5.90.0", kind:"page", ref:"pgWf",
    t:{my:"အသစ်ထွက်တာတွေ ချက်ချင်းသိရပါပြီ",en:"You'll see what's new, straight away",shn:"တေႁၼ်ၶိူင်ႈမႂ်ႇတင်းသဵင်ႈ",kac:"Nnan ai ni hpe mu na",th:"เห็นของใหม่ได้ทันที",zh:"新功能一眼就看到",vi:"Thấy ngay cái mới",id:"Langsung lihat yang baru",ms:"Terus nampak yang baharu"},
    s:{my:"ကတ်အသစ်တွေမှာ ရွှေရောင် NEW တံဆိပ် တပ်ထားပြီး အပေါ်ဆုံးမှာ ပြပါတယ် — နှိပ်ပြီး ချက်ချင်းစမ်းလို့ရပါတယ်",en:"New cards wear a gold NEW mark and sit at the top of their group — tap to try one now",shn:"ၶႅပ်းမႂ်ႇမီးမၢႆ NEW သီၶမ်း",kac:"Nnan ai card ni gold NEW lam tsun",th:"การ์ดใหม่มีป้าย NEW สีทองและอยู่บนสุด",zh:"新卡片带金色 NEW 标记并排在最前",vi:"Thẻ mới có nhãn NEW vàng và nằm trên cùng",id:"Kartu baru bertanda NEW emas dan ada di paling atas",ms:"Kad baharu bertanda NEW emas di bahagian atas"} },
  { v:"5.89.0", kind:"page", ref:"pgVideo",
    t:{my:"Video model အသစ် ၁၂ ခု",en:"Twelve new video models",shn:"ဝီးတီးဢူဝ်း model မႂ်ႇ 12",kac:"Video model nnan 12",th:"โมเดลวิดีโอใหม่ 12 ตัว",zh:"12 个新视频模型",vi:"12 mô hình video mới",id:"12 model video baru",ms:"12 model video baharu"},
    s:{my:"MiniMax H3 Max, H3 Context-IR (အသံပါ), Gemini Omni 1.1 Flash နဲ့ 768P ကို 2K ပြန်ထုတ်တဲ့ tool တွေ",en:"MiniMax H3 Max, H3 Context-IR (with sound), Gemini Omni 1.1 Flash, and 768P→2K regeneration tools",shn:"MiniMax H3 Max, Context-IR, Gemini Omni 1.1",kac:"MiniMax H3 Max, Context-IR, Gemini Omni 1.1",th:"MiniMax H3 Max, Context-IR (มีเสียง), Gemini Omni 1.1",zh:"MiniMax H3 Max、Context-IR（带声音）、Gemini Omni 1.1",vi:"MiniMax H3 Max, Context-IR (có tiếng), Gemini Omni 1.1",id:"MiniMax H3 Max, Context-IR (bersuara), Gemini Omni 1.1",ms:"MiniMax H3 Max, Context-IR (berbunyi), Gemini Omni 1.1"} },
  { v:"5.87.0", kind:"wf", ref:"studio-look-copy",
    t:{my:"Studio Look Copy",en:"Studio Look Copy",shn:"Studio Look Copy",kac:"Studio Look Copy",th:"Studio Look Copy",zh:"Studio Look Copy",vi:"Studio Look Copy",id:"Studio Look Copy",ms:"Studio Look Copy"},
    s:{my:"နမူနာပုံတစ်ပုံရဲ့ အရောင်၊ အလင်း၊ အသားရေ၊ scene အကုန်လုံးကို ကိုယ့်ပုံဆီ ကူးယူပေးတယ် — ပုံရာနဲ့ချီ တစ်ပုံစံတည်း",en:"Copies one reference photo's whole scene, colour, light and skin into your photo — the same look across a hundred frames",shn:"လၢႆးသီ လႄႈ ၾႆး ၶွင်ၶႅပ်းၼမူႇ",kac:"Reference sumla a nsam hte nhtoi",th:"คัดลอกโทนสี แสง ผิว ทั้งฉากจากรูปอ้างอิง",zh:"把参考照片的场景、色彩、光线和肤质整套复制到你的照片",vi:"Sao chép toàn bộ bối cảnh, màu, ánh sáng và da từ ảnh mẫu",id:"Menyalin seluruh suasana, warna, cahaya dan kulit dari foto acuan",ms:"Menyalin seluruh suasana, warna, cahaya dan kulit dari foto rujukan"} },
  { v:"5.86.0", kind:"page", ref:"pgGallery",
    t:{my:"ရလဒ်တွေ အလိုအလျောက် သိမ်းထားပြီ",en:"Your results are kept automatically",shn:"ၽွၼ်းလႆႈ လႆႈသိမ်းဝႆႉ",kac:"Nan a lam ni hpe makawp",th:"ผลงานถูกเก็บอัตโนมัติ",zh:"生成结果会自动保存",vi:"Kết quả được lưu tự động",id:"Hasil tersimpan otomatis",ms:"Hasil disimpan automatik"},
    s:{my:"Tab ပိတ်သွားရင်တောင် ရလဒ်တွေ Gallery ထဲမှာ ကျန်နေမယ် — ကိုယ်တိုင်ဖျက်မှ ပျောက်မယ်",en:"Close the tab and the results are still in your Gallery — they go only when you delete them",shn:"ပိၵ်း tab သေတႃႉ ၽွၼ်းလႆႈယင်းမီး",kac:"Tab la kau tim Gallery hta naw nga",th:"ปิดแท็บแล้วผลงานยังอยู่ในแกลเลอรี",zh:"关掉分页，结果仍在图库里",vi:"Đóng tab, kết quả vẫn còn trong Thư viện",id:"Tutup tab, hasil tetap ada di Galeri",ms:"Tutup tab, hasil kekal dalam Galeri"} }
];

var API = { LIST: WHATS_NEW,
  key: function (e) { return e.v + "|" + e.ref; },
  /* the panel keeps its own read-record: the same student on the same
     machine, but UXP storage is not the browser's localStorage, so a card
     read on the phone stays new in Photoshop and vice versa. That is the
     honest behaviour — neither surface can see the other's storage. */
  SEEN_KEY: "hnk_new_seen" };

if (typeof module !== "undefined" && module.exports) module.exports = API;
else { globalThis.HNK = globalThis.HNK || {}; globalThis.HNK.whatsNew = API; }
})();
