/* ============================================================
   HNK "what's new" list — LIFTED, do not edit by hand.
   Source of truth: the web app's own WHATS_NEW table
   (docs/app/index.html), copied verbatim so a student is told the
   same thing in Photoshop as on their phone, in the same words and
   the same nine languages. test/verify_panel_whats_new.js pins this
   file to the app's, entry for entry.
   ============================================================ */
(function () {
"use strict";
var WHATS_NEW = [
  { v:"6.8.0", kind:"page", ref:"pgAccount",
    t:{my:"Register ပြီးရင် ထွက်ပြီး ပြန်ဝင်စရာ မလိုတော့ပါ",en:"After registering, you no longer sign out and back in",shn:"ႁဵတ်းမၢႆၽၢင်ယဝ်ႉ ဢမ်ႇလူဝ်ႇဢွၵ်ႇသေၶဝ်ႈမႂ်ႇ",kac:"Matsun ngut yang pru nna bai shang ra n nga sai",th:"สมัครแล้วไม่ต้องออกแล้วเข้าใหม่อีก",zh:"注册后不再需要退出再登录",vi:"Đăng ký xong không cần đăng xuất rồi đăng nhập lại",id:"Setelah mendaftar, tidak perlu keluar lalu masuk lagi",ms:"Selepas mendaftar, tidak perlu log keluar dan masuk semula"},
    s:{my:"အရင်က register ပြီးတာနဲ့ \"ငွေပေးပါ\" စာမျက်နှာ ပေါ်နေပြီး၊ HNK က ခွင့်ပြုပြီးမှ ၅ မိနစ်ကြာမှ ပွင့်တာမို့ သင်တန်းသားတွေ ထွက်ပြီး ပြန်ဝင်နေရတယ်။ အခု register ပြီးရင် \"HNK စစ်ဆေးနေပါတယ်\" လို့ မှန်မှန် ပြောပြီး ၂၀ စက္ကန့်တစ်ခါ ပြန်စစ်ပါတယ် — ခွင့်ပြုတာနဲ့ ရပ်နေတဲ့ နေရာမှာတင် အလိုအလျောက် ပွင့်ပြီး ကြိုဆိုစာ ပေါ်ပါမယ်။",
       en:"A student who had just registered was shown the PAY screen, and approval only reached them up to five minutes later — so people signed out and back in to get through. The app now says plainly \"HNK is checking your account\", asks again every twenty seconds, and the moment you are approved the page opens where you stand and says so.",
       shn:"ႁဵတ်းမၢႆၽၢင်ယဝ်ႉ ၼႃႈလိၵ်ႈ \"ပၼ်ငိုၼ်း\" ဢွၵ်ႇမႃး — ယၢမ်းလဵဝ် လၢတ်ႈဝႃႈ HNK တိုၵ်ႉၸႅတ်ႈ လႄႈ ၸႅတ်ႈမႂ်ႇ ၵူႈ ၂၀ ၸႅတ်ႉၵၼ်ႉ၊ ၶႂ်ႈလႆႈယဝ်ႉ ပိုတ်ႇႁင်းၵူၺ်း",
       kac:"Matsun ngut ai hpang \"gumhpraw jaw\" laika ka pru wa ai — ya gaw HNK yu nga ai nga tsun, 20 second langai lang bai yu, shapraw ngut ai hte shi hkrai hpaw ai",
       th:"หลังสมัคร เคยเห็นหน้า \"ชำระเงิน\" และการอนุมัติมาถึงช้าถึงห้านาที คนจึงออกแล้วเข้าใหม่ ตอนนี้แอปบอกตรง ๆ ว่า HNK กำลังตรวจสอบ ถามใหม่ทุก 20 วินาที และเมื่ออนุมัติ หน้าจะเปิดเองทันที",
       zh:"刚注册的学员会看到\"付款\"页面，审核结果最多要五分钟才到，所以大家只能退出再登录。现在应用会直说 HNK 正在审核，每 20 秒重查一次，通过的那一刻页面就地打开并提示你。",
       vi:"Học viên vừa đăng ký lại thấy màn hình \"thanh toán\", và phê duyệt chỉ đến sau tới năm phút — nên mọi người đăng xuất rồi đăng nhập lại. Giờ ứng dụng nói rõ HNK đang kiểm tra, hỏi lại mỗi 20 giây, và được duyệt là trang mở ngay tại chỗ.",
       id:"Siswa yang baru mendaftar malah melihat layar \"bayar\", dan persetujuan baru sampai hingga lima menit kemudian — jadi orang keluar lalu masuk lagi. Kini aplikasi berkata jujur HNK sedang memeriksa, bertanya lagi tiap 20 detik, dan begitu disetujui halaman terbuka di tempat.",
       ms:"Pelajar yang baru mendaftar melihat skrin \"bayar\", dan kelulusan hanya sampai sehingga lima minit kemudian — jadi orang log keluar dan masuk semula. Kini aplikasi berkata terus HNK sedang menyemak, bertanya lagi setiap 20 saat, dan sebaik diluluskan halaman terbuka di situ juga."} },
  { v:"6.7.0", kind:"page", ref:"pgRetouch",
    t:{my:"HD Finish ကို ကိုယ်တိုင် ရွေးလို့ရပြီ",en:"You choose how the HD Finish works",shn:"လိူၵ်ႈ HD Finish လႆႈယဝ်ႉ",kac:"HD Finish hpe nang lata lu sai",th:"เลือกวิธี HD Finish ได้เองแล้ว",zh:"HD Finish 现在由你决定",vi:"Bạn tự chọn cách HD Finish chạy",id:"Anda yang memilih cara HD Finish bekerja",ms:"Anda pilih cara HD Finish berfungsi"},
    s:{my:"Retouch A၊ Retouch B၊ Retouch Pro သုံးခုလုံးရဲ့ HD Finish က engine တစ်ခုတည်းနဲ့ ပုံသေ လုပ်နေခဲ့တာ — ပြီးတော့ RunningHub ရဲ့ default အရ မျက်နှာကို Topaz က ထပ်ပြင်နေတယ်၊ သင် သေချာပြင်ထားတဲ့ အသားအရေ ပျက်သွားနိုင်တယ်။ အခု Retouch Pro ထဲမှာ engine ငါးမျိုး (ပုံမှန်၊ မျက်နှာ အသေးစိတ်၊ ပရင့်ထုတ်၊ ပုံသေး/ဓာတ်ပုံဟောင်း၊ HYPIR ပြန်လည်ပြုပြင်) ရွေးလို့ရပြီး၊ \"ငါ့ retouch ကို မထိနဲ့\" လို့လည်း ပြောလို့ရပါပြီ။ ရွေးလိုက်တာက သုံးမျက်နှာလုံးအတွက် တူတူပါပဲ။",
       en:"The HD Finish behind Retouch A, Retouch B and Retouch Pro was one fixed engine — and RunningHub's default let Topaz re-work the face on top of the skin retouch you had just paid for. Retouch Pro now offers five engines (Standard, Face detail, For print, Small or old photo, HYPIR restore) and lets you say \"keep my retouch\" so the face pass stays off. The choice is shared by all three pages.",
       shn:"HD Finish တႃႇ Retouch A, B လႄႈ Pro ၸႂ်ႉ engine လဵဝ်ၵူၺ်း — ယၢမ်းလဵဝ် လိူၵ်ႈလႆႈ ႁႃႈမဵဝ်း လႄႈ ဢွၼ်ႇပိၵ်ႉ face pass လႆႈ",
       kac:"Retouch A, B, Pro ni a HD Finish gaw engine langai sha nga ai — ya gaw manga lata lu, myiman pass mung sat lu ai",
       th:"HD Finish ของ Retouch A, B และ Pro เคยใช้เอนจินเดียวตายตัว และค่าเริ่มต้นของ RunningHub ปล่อยให้ Topaz แก้ใบหน้าทับรีทัชที่คุณเพิ่งทำ ตอนนี้เลือกได้ 5 เอนจิน และสั่ง \"อย่าแตะรีทัชของฉัน\" ได้",
       zh:"Retouch A、B、Pro 的 HD Finish 过去固定用一个引擎，而 RunningHub 的默认设置会让 Topaz 在你刚做好的精修之上重做面部。现在可选五种引擎，也可以要求保留你的精修。",
       vi:"HD Finish của Retouch A, B và Pro trước đây cố định một engine, và mặc định của RunningHub để Topaz làm lại khuôn mặt đè lên bản retouch bạn vừa trả tiền. Giờ có năm engine và tuỳ chọn giữ nguyên bản retouch.",
       id:"HD Finish di Retouch A, B dan Pro dulu satu engine tetap, dan default RunningHub membiarkan Topaz mengolah ulang wajah di atas retouch Anda. Kini ada lima engine dan opsi mempertahankan retouch Anda.",
       ms:"HD Finish pada Retouch A, B dan Pro dahulu satu engine tetap, dan lalai RunningHub membiarkan Topaz mengolah semula wajah atas retouch anda. Kini ada lima engine dan pilihan mengekalkan retouch anda."} },
  { v:"6.6.0", kind:"page", ref:"pgV2V",
    t:{my:"မျက်နှာ + ဆံပင် လဲတဲ့ ကတ် အသစ်",en:"A new card: face and hair together",shn:"ၵၢတ်ႉမႂ်ႇ — လႅၵ်ႈၼႃႈလႄႈၽိူၼ်း",kac:"Kat nnan — myiman hte kara galai",th:"การ์ดใหม่: เปลี่ยนทั้งหน้าและผม",zh:"新卡片：脸和发型一起换",vi:"Thẻ mới: đổi cả mặt lẫn tóc",id:"Kartu baru: wajah dan rambut sekaligus",ms:"Kad baharu: wajah dan rambut sekali"},
    s:{my:"VIDEO → VIDEO မှာ ကတ် ဆယ်ခုမြောက် ပါလာပါပြီ။ \"မျက်နှာပဲ လဲမယ်\" ကတ်က ဆံပင်ကိုပါ တစ်ခါတလေ ပြောင်းသွားတတ်လို့ — အဲ့ဒါ model ရဲ့ သဘာဝပါ — အခု တစ်ကယ်ထွက်လာတဲ့ ရလဒ်အတိုင်း အတိအကျ ရေးထားတဲ့ ကတ်အသစ် ထပ်ထည့်ပေးလိုက်ပါတယ်: မျက်နှာနဲ့ ဆံပင် နှစ်ခုလုံး ပုံထဲကလို ဖြစ်သွားပြီး၊ လည်ပင်းအောက် ကိုယ်လုံး၊ အဝတ်အစား၊ နေရာ အတိုင်း ကျန်ပါမယ်။ ရှိပြီးသား ကတ်ကို မထိထားပါဘူး။",en:"VIDEO → VIDEO gains a tenth card. The \"face only\" card sometimes brings the hair across as well — that is the model's behaviour, not a setting — so rather than change a card you already use, here is a new one that says exactly what comes out: the face AND the hair become the person in your photo, while the body, the clothes and the scene below the neck stay as filmed.",shn:"VIDEO → VIDEO မီးၵၢတ်ႉဢၼ်ထူၼ်ႈသိပ်း — လႅၵ်ႈၼႃႈလႄႈၽိူၼ်းၶူဝ်း၊ တူဝ်ၶိင်းလႄႈတီႈ ဢမ်ႇလႅၵ်ႈ",kac:"VIDEO → VIDEO hta kat shi ngu ai nnan nga sai — myiman hte kara galai, hkum hte shara n galai",th:"VIDEO → VIDEO มีการ์ดใบที่สิบ การ์ด \"เปลี่ยนแค่ใบหน้า\" บางครั้งเปลี่ยนผมมาด้วย ซึ่งเป็นพฤติกรรมของโมเดลเอง จึงเพิ่มการ์ดใหม่ที่บอกตรง ๆ ว่าได้อะไร: ทั้งใบหน้าและผมจะกลายเป็นคนในรูปของคุณ ส่วนลำตัว เสื้อผ้า และฉากใต้คอคงเดิม",zh:"VIDEO → VIDEO 增加第十张卡。\"只换脸\"那张有时会连发型一起换 — 这是模型本身的行为 — 与其改动你已经在用的卡片，不如新增一张把结果说清楚的：脸和发型都会变成你照片里的人，脖子以下的身形、服装和场景保持原样。",vi:"VIDEO → VIDEO có thẻ thứ mười. Thẻ \"chỉ đổi khuôn mặt\" đôi khi đổi cả tóc — đó là hành vi của mô hình — nên thay vì sửa thẻ bạn đang dùng, đây là thẻ mới nói đúng kết quả: khuôn mặt VÀ mái tóc thành người trong ảnh của bạn, còn thân người, trang phục và bối cảnh dưới cổ giữ nguyên.",id:"VIDEO → VIDEO mendapat kartu kesepuluh. Kartu \"ganti wajah saja\" kadang ikut mengganti rambut — itu perilaku modelnya — jadi alih-alih mengubah kartu yang sudah Anda pakai, ini kartu baru yang menyebutkan hasilnya apa adanya: wajah DAN rambut menjadi orang di foto Anda, sementara tubuh, pakaian, dan latar di bawah leher tetap.",ms:"VIDEO → VIDEO mendapat kad kesepuluh. Kad \"tukar wajah sahaja\" kadangkala turut menukar rambut — itu perilaku modelnya — jadi daripada mengubah kad yang anda sudah guna, ini kad baharu yang menyatakan hasilnya dengan jujur: wajah DAN rambut menjadi orang dalam foto anda, manakala badan, pakaian dan latar di bawah leher kekal."} },
  { v:"6.5.0", kind:"page", ref:"pgTalk",
    t:{my:"ပုံတစ်ပုံကို စကားပြောခိုင်းလို့ ရပါပြီ",en:"Your photo can talk now",shn:"ႁဵတ်းႁႂ်ႈၶႅပ်းႁၢင်ႈလၢတ်ႈၵႂၢမ်းလႆႈယဝ်ႉ",kac:"Nang a sumla ga shaga lu sai",th:"ทำให้รูปของคุณพูดได้แล้ว",zh:"你的照片会说话了",vi:"Ảnh của bạn đã biết nói",id:"Foto Anda kini bisa berbicara",ms:"Foto anda kini boleh bercakap"},
    s:{my:"Media Lab ထဲမှာ TALK စာမျက်နှာ အသစ် ပါလာပါပြီ — ပုံတစ်ပုံနဲ့ အသံဖိုင်တစ်ခု ထည့်လိုက်ရုံနဲ့ ပုံထဲက လူက အဲ့ဒီအသံအတိုင်း နှုတ်ခမ်းလှုပ်ပြီး စကားပြောပေးပါမယ်။ ကိုယ်တိုင် အသံသွင်းထားတာ သုံးလို့ရလို့ မြန်မာလို ဖြစ်ဖြစ် ဘယ်ဘာသာစကားနဲ့ဖြစ်ဖြစ် ရပါတယ်။ တစ်စက္ကန့် ဘယ်လောက်ကျမလဲဆိုတာ Generate မနှိပ်ခင် ကြိုပြပေးထားပါတယ်။",en:"Media Lab has a new TALK page: add a photo and an audio file, and the person in the photo lip-syncs it. Because you supply the recording, it works in Burmese or any other language. The per-second price is shown before you press Generate, since RunningHub charges at submit.",shn:"ၼႂ်း Media Lab မီးၼႃႈလိၵ်ႈ TALK မႂ်ႇ — သႂ်ႇၶႅပ်းႁၢင်ႈလႄႈၾၢႆႇသဵင် ၵေႃႉၼႂ်းၶႅပ်းတေလၢတ်ႈၸွမ်း။ ၸႂ်ႉသဵင်ႁင်းၵူၺ်းလႆႈ ၵူႈၽႃႇသႃႇ",kac:"Media Lab hta TALK laika nnan nga sai — sumla langai hte nsen file langai bang yang sumla hta na masha gaw dai hte ga shaga na re. Nang nan nsen jaw ai majaw ga amyu hkum hkra byin ai",th:"Media Lab มีหน้า TALK ใหม่ — ใส่รูปและไฟล์เสียง แล้วคนในรูปจะขยับปากพูดตาม เพราะคุณเป็นคนใส่เสียงเอง จึงใช้ได้ทั้งภาษาพม่าและภาษาอื่น ๆ ราคาต่อวินาทีจะแสดงก่อนกด Generate",zh:"Media Lab 新增 TALK 页面：放一张照片和一个音频文件，照片里的人就会对口型说出来。声音由你提供，所以缅语或任何语言都可以。每秒价格在按下生成之前就先告诉你。",vi:"Media Lab có trang TALK mới: thêm một ảnh và một tệp âm thanh, người trong ảnh sẽ nhép miệng nói theo. Vì bạn tự cung cấp bản ghi nên dùng được tiếng Miến hay bất kỳ ngôn ngữ nào. Giá mỗi giây hiện ra trước khi bạn bấm Generate.",id:"Media Lab punya halaman TALK baru: tambahkan foto dan file audio, lalu orang di foto akan menyelaraskan bibirnya. Karena rekaman dari Anda, bahasa apa pun bisa. Harga per detik tampil sebelum menekan Generate.",ms:"Media Lab kini ada halaman TALK: tambah foto dan fail audio, dan orang dalam foto akan menyelaraskan bibirnya. Kerana rakaman datang daripada anda, mana-mana bahasa boleh. Harga sesaat dipaparkan sebelum anda tekan Generate."} },
  { v:"6.4.0", kind:"page", ref:"pgV2V",
    t:{my:"အပြင်ထွက်သွားလည်း အလုပ်က ဆက်လုပ်နေမယ်",en:"Leave the app and the work keeps going",shn:"ဢွၵ်ႇၵႂႃႇသေတႃႉ ၵၢၼ်ယင်းသိုပ်ႇႁဵတ်းယူႇ",kac:"Pru mat tim bungli gaw naw galaw nga na",th:"ออกจากแอปไปแล้วงานก็ยังทำต่อ",zh:"离开 App，任务照样继续跑",vi:"Rời ứng dụng, việc vẫn chạy tiếp",id:"Tinggalkan aplikasi, pekerjaannya tetap jalan",ms:"Tinggalkan aplikasi, kerjanya tetap berjalan"},
    s:{my:"Generate နှိပ်ပြီး app ကနေ ထွက်သွားရင်တောင် RunningHub ဘက်မှာ ဆက်လုပ်နေပါတယ် — ပြန်ဝင်တာနဲ့ ရလဒ်ကို အလိုအလျောက် ကောက်ယူပေးမယ်၊ ရလဒ်ထွက်တဲ့အထိ စောင့်ကြည့်ပေးမယ်။ VIDEO → VIDEO က ရလဒ်တွေကိုလည်း သိမ်းထားပြီး စာမျက်နှာ ပြန်ဖွင့်ရင် ပြန်ပေါ်ပါမယ် — ကိုယ်တိုင် မဖျက်မချင်း ကျန်နေပါမယ်။ ရွေးထားတဲ့ ဗီဒီယိုနဲ့ ပုံကိုလည်း နာမည်တင်မဟုတ်တော့ဘဲ ပုံအနေနဲ့ မြင်ရပြီး၊ ကြာချိန်ပါ ပြပါတယ်။",en:"Press Generate and leave — RunningHub keeps rendering, and coming back collects the result by itself; the app now watches until it arrives instead of checking once. VIDEO → VIDEO keeps its results too: they are saved as they finish and are on the page again when you open it, and they stay until you delete them. The clip and the photo you picked are shown as a clip and a photo, with the clip\u2019s length, instead of two filenames.",shn:"ၼဵၵ်း Generate သေဢွၵ်ႇၵႂႃႇလႆႈ — RunningHub သိုပ်ႇႁဵတ်းယူႇ၊ ၶဝ်ႈမႃးၶိုၼ်း တေဢဝ်ၽွၼ်းလႆႈပၼ်ႁင်းၵူၺ်း။ ၽွၼ်းလႆႈ VIDEO → VIDEO လႆႈသိမ်းဝႆႉ။ ဝီဒီရူဝ်ႈလႄႈၶႅပ်းႁၢင်ႈဢၼ်လိူၵ်ႈဝႆႉ ႁၼ်ပဵၼ်ႁၢင်ႈ",kac:"Generate dip nna pru mat tim RunningHub gaw naw galaw nga ai — bai shang wa yang ah kyu hpe shi hkrai la la ai. VIDEO → VIDEO na ah kyu ni mung makawp da nna shara hpaw yang bai mu na. Lata da ai video hte sumla mung mying sha n re, sumla hku mu na",th:"กด Generate แล้วออกจากแอปได้เลย — RunningHub ยังเรนเดอร์ต่อ และเมื่อกลับเข้ามาระบบจะเก็บผลลัพธ์ให้เอง โดยเฝ้ารอจนกว่าจะได้ผล หน้า VIDEO → VIDEO ยังเก็บผลงานไว้ด้วย เปิดหน้าเมื่อไรก็เห็นอีก และอยู่จนกว่าคุณจะลบเอง ส่วนคลิปกับรูปที่เลือกไว้จะแสดงเป็นคลิปและรูปพร้อมความยาว แทนที่จะเป็นชื่อไฟล์",zh:"按下 Generate 就可以离开 — RunningHub 会继续渲染，回来时结果会自动取回，而且会一直守到结果出来，不再只查一次。VIDEO → VIDEO 的结果也会保存，重新打开页面就还在，删掉之前一直都在。选好的视频和照片现在显示为视频和照片本身（还带时长），而不是两行文件名。",vi:"Bấm Generate rồi rời đi — RunningHub vẫn dựng tiếp, và khi quay lại ứng dụng tự lấy kết quả về; nó theo dõi cho tới khi kết quả tới thay vì chỉ kiểm tra một lần. Trang VIDEO → VIDEO cũng giữ kết quả: mở lại là thấy, và còn nguyên cho tới khi bạn xoá. Clip và ảnh bạn đã chọn hiện ra đúng là clip và ảnh, kèm độ dài, thay vì hai tên tệp.",id:"Tekan Generate lalu tinggalkan — RunningHub tetap merender, dan saat kembali hasilnya diambil sendiri; aplikasi menunggu sampai hasilnya datang, bukan sekali cek. Halaman VIDEO → VIDEO juga menyimpan hasilnya: ada lagi saat dibuka, dan bertahan sampai Anda menghapusnya. Klip dan foto yang dipilih kini tampil sebagai klip dan foto beserta durasinya, bukan dua nama file.",ms:"Tekan Generate dan pergi — RunningHub terus render, dan bila anda kembali hasilnya diambil sendiri; aplikasi menunggu sehingga hasil tiba, bukan sekadar semak sekali. Halaman VIDEO → VIDEO turut menyimpan hasilnya: ada semula bila dibuka, dan kekal sehingga anda memadamnya. Klip dan foto yang dipilih kini dipaparkan sebagai klip dan foto berserta durasinya, bukan dua nama fail."} },
  { v:"6.3.0", kind:"page", ref:"pgV2V",
    t:{my:"ဗီဒီယို ကတ် ၇ ခု ထပ်တိုး — ရုပ်ပြောင်း၊ ရှည်အောင်၊ ရှင်းအောင်",en:"Seven more video cards — restyle it, stretch it, clean it up",shn:"ၵၢတ်ႉဝီဒီရူဝ်ႈ 7 ဢၼ်မႂ်ႇ — လႅၵ်ႈႁၢင်ႈ၊ ႁဵတ်းႁႂ်ႈယၢဝ်း၊ ႁဵတ်းႁႂ်ႈၸႅင်ႈ",kac:"Video kat 7 nnan — hkrang galai, galu galaw, san seng galaw",th:"การ์ดวิดีโอใหม่ 7 ใบ — เปลี่ยนสไตล์ ต่อให้ยาว ทำให้คมชัด",zh:"新增 7 张视频卡 — 换风格、加长、修清晰",vi:"Bảy thẻ video mới — đổi phong cách, kéo dài, làm nét",id:"Tujuh kartu video baru — ubah gaya, perpanjang, pertajam",ms:"Tujuh kad video baharu — tukar gaya, panjangkan, tajamkan"},
    s:{my:"VIDEO → VIDEO စာမျက်နှာမှာ ကတ် ၉ ခု ပြည့်သွားပါပြီ — ကာတွန်း/အန်နီမေး ပြောင်း၊ ရုပ်ရှင်အရောင် တင်၊ ရှေးဟောင်း အသွင်၊ ဗီဒီယို ဆက်ရှည်၊ ဟောင်းတဲ့ဗီဒီယို ကြည်လင်အောင်၊ စာတန်းထိုး ဖျက်၊ ၃၀ စက္ကန့်အထိ ဇာတ်ကောင် ထည့် — ကတ်တစ်ချက် နှိပ်ရုံနဲ့ tool ရော prompt ရော အဆင်သင့်။",en:"The VIDEO → VIDEO page now has all nine cards: turn a clip into anime or cartoon, grade it like film, give it a heritage look, make it longer, sharpen an old clip, erase burnt-in subtitles, or put your character into a clip up to 30 seconds — one tap sets the tool and writes the whole request.",shn:"ၼႃႈလိၵ်ႈ VIDEO → VIDEO မီးၵၢတ်ႉ 9 ဢၼ်ယဝ်ႉ — လႅၵ်ႈပဵၼ်ၵႃႇတုၼ်း၊ သီၼင်ႇလိပ်း၊ ႁၢင်ႈၵဝ်ႇ၊ ႁဵတ်းႁႂ်ႈယၢဝ်း၊ မႄးဝီဒီရူဝ်ႈၵဝ်ႇ၊ လုပ်ႇလိၵ်ႈၼိူဝ်ငဝ်း၊ သႂ်ႇတူဝ်ၸဝ်ႈၵဝ်ႇထိုင် 30 ၸဵၵ်ႇ — ၼဵၵ်းၵၢတ်ႉပွၵ်ႈလဵဝ် tool လႄႈ prompt တဵမ်ထူၼ်ႈ။",kac:"VIDEO → VIDEO shara kaw kat 9 hkum sai — cartoon hte anime galai, sumla hkrang zawn nsam jaw, moi hkrang jaw, video galu galaw, video dingsa san seng galaw, ntsa na laika mat kau, 30 sekan du hkra na masha bang — kat langai dip yang tool hte prompt yawng hkum sai.",th:"หน้า VIDEO → VIDEO มีการ์ดครบ 9 ใบแล้ว ทั้งเปลี่ยนเป็นอนิเมะหรือการ์ตูน เกรดสีแบบหนัง ลุคย้อนยุค ต่อคลิปให้ยาวขึ้น กู้คลิปเก่าให้คมชัด ลบซับที่ฝังในภาพ และใส่ตัวละครของคุณลงคลิปยาวถึง 30 วินาที — แตะการ์ดเดียว ได้ทั้งเครื่องมือและ prompt ครบ",zh:"VIDEO → VIDEO 页面现在共有 9 张卡：转成动漫或卡通、电影感调色、复古质感、把片子接长、修复模糊老片、擦掉硬字幕、把你的角色放进最长 30 秒的片子 — 点一下卡片，工具和 prompt 一次写好。",vi:"Trang VIDEO → VIDEO giờ có đủ 9 thẻ: chuyển thành anime hay hoạt hình, chỉnh màu như phim, sắc thái hoài cổ, kéo dài clip, phục hồi clip cũ cho nét, xoá phụ đề cháy hình, và đưa nhân vật của bạn vào clip dài tới 30 giây — chạm một thẻ là có sẵn cả công cụ lẫn prompt.",id:"Halaman VIDEO → VIDEO kini punya sembilan kartu: ubah jadi anime atau kartun, gradasi warna ala film, nuansa klasik, perpanjang klip, pulihkan klip lama jadi tajam, hapus subtitle yang menyatu, dan masukkan karakter Anda ke klip hingga 30 detik — satu ketukan menyiapkan alat sekaligus prompt-nya.",ms:"Halaman VIDEO → VIDEO kini ada sembilan kad: tukar jadi anime atau kartun, gred warna seperti filem, rupa klasik, panjangkan klip, pulihkan klip lama jadi tajam, padam sarikata terbakar, dan masukkan watak anda ke dalam klip sehingga 30 saat — satu ketikan menyediakan alat dan gesaannya sekali."} },
  { v:"6.2.0", kind:"page", ref:"pgV2V",
    t:{my:"ဗီဒီယိုနဲ့ လုပ်စရာအားလုံး စာမျက်နှာ အသစ်တစ်ခုမှာ",en:"Everything you do to a video now has its own page",shn:"ၵၢၼ်ဝီဒီရူဝ်ႈတင်းသဵင်ႈ မီးၼႃႈလိၵ်ႈမႂ်ႇ",kac:"Video hte galaw ai yawng gaw shara nnan langai lu sai",th:"ทุกอย่างที่ทำกับวิดีโอ มีหน้าของตัวเองแล้ว",zh:"所有对视频的处理现在有了自己的页面",vi:"Mọi thao tác với video giờ có trang riêng",id:"Semua yang Anda lakukan pada video kini punya halamannya sendiri",ms:"Segala yang anda buat pada video kini ada halamannya sendiri"},
    s:{my:"Media Lab ထဲမှာ VIDEO → VIDEO ဆိုတဲ့ စာမျက်နှာ အသစ် တစ်ခု ထပ်တိုးလိုက်ပါပြီ။ ဗီဒီယိုတစ်ခု ထည့်ပြီး ဗီဒီယိုပြန်ထွက်တဲ့ tool ၃၁ ခုလုံးနဲ့ smart ကတ်တွေ အဲ့ဒီမှာ စုထားပါတယ် — အရင်က VidUp စာမျက်နှာရဲ့ အောက်ခြေမှာ ဝှက်နေခဲ့တာ။ VidUp မှာတော့ Upscale တစ်ခုတည်း ကျန်ပါတယ်။ endpoint အသစ် ထပ်မထည့်ပါ — ရှိပြီးသားတွေကို ရှာလို့ရအောင် လုပ်လိုက်တာပါ",en:"Media Lab has a new page, VIDEO → VIDEO. All thirty-one tools that take a video in and give a video back live there now, together with the smart cards — they used to sit below the fold of a page named after Upscale. VidUp keeps Upscale and nothing else. Not one endpoint was added: the same catalog, reachable",shn:"Media Lab မီးၼႃႈလိၵ်ႈမႂ်ႇ VIDEO → VIDEO — tool 31 ဢၼ်တင်းသဵင်ႈ မီးတီႈၼၼ်ႈ",kac:"Media Lab hta shara nnan VIDEO → VIDEO — tool 31 ting dai kaw nga sai",th:"Media Lab มีหน้าใหม่ VIDEO → VIDEO รวมเครื่องมือวิดีโอทั้ง 31 ตัวและการ์ดอัจฉริยะไว้ที่เดียว ส่วน VidUp เหลือแค่ Upscale",zh:"Media Lab 新增 VIDEO → VIDEO 页面，三十一个视频进视频出的工具和智能卡片都在这里；VidUp 只保留放大。没有新增任何端点，只是让原有的能被找到",vi:"Media Lab có trang mới VIDEO → VIDEO: cả ba mươi mốt công cụ video-vào-video và các thẻ thông minh đều ở đó; VidUp chỉ còn Upscale. Không thêm endpoint nào — chỉ là tìm được",id:"Media Lab punya halaman baru VIDEO → VIDEO: ketiga puluh satu alat video-ke-video dan kartu pintarnya ada di sana; VidUp hanya menyisakan Upscale. Tidak ada endpoint baru — hanya jadi bisa ditemukan",ms:"Media Lab ada halaman baharu VIDEO → VIDEO: kesemua tiga puluh satu alat video-ke-video dan kad pintarnya ada di situ; VidUp kekal Upscale sahaja. Tiada endpoint baharu — cuma kini boleh dijumpai"} },
  { v:"6.1.0", kind:"page", ref:"pgV2V",
    t:{my:"ကြိုက်တဲ့ ဗီဒီယိုထဲကို ကိုယ့်ဇာတ်ကောင် ထည့်လို့ရပါပြီ",en:"Your own character can now go into any clip you like",shn:"သႂ်ႇတူဝ်ၸဝ်ႈၵဝ်ႇၶဝ်ႈၼႂ်းဝီဒီရူဝ်ႈလႆႈယဝ်ႉ",kac:"Video hta nang a masha bang lu sai",th:"ใส่ตัวละครของคุณลงในคลิปที่ชอบได้แล้ว",zh:"现在可以把你的角色放进任意视频",vi:"Giờ bạn có thể đưa nhân vật của mình vào clip bất kỳ",id:"Karakter Anda kini bisa masuk ke klip mana pun",ms:"Watak anda kini boleh masuk ke dalam mana-mana klip"},
    s:{my:"Video Tools မှာ ကတ် ၂ ခု အသစ် — တစ်ခုက ဗီဒီယိုထဲက လူတစ်ယောက်လုံးကို ကိုယ့်ပုံနဲ့ အစားထိုးပေးတယ်၊ နောက်တစ်ခုက မျက်နှာပဲ လဲပေးတယ်။ ကင်မရာလှုပ်ရှားမှု၊ လှုပ်ရှားချိန်၊ နောက်ခံ၊ အသံ အားလုံး မူရင်းအတိုင်း ကျန်ပါတယ်။ ကတ်တစ်ချက်နှိပ်ရုံနဲ့ tool ရွေးပေးပြီး prompt ရေးပေးမယ် — ဗီဒီယိုက ၁၀ စက္ကန့်အထိ",en:"Two new cards on Video Tools — one replaces the whole person in the clip with the one in your photo, the other changes only the face. The camera move, the timing, the background and the original sound all stay as filmed. One tap picks the tool and writes the request; the clip may run up to ten seconds",shn:"ၵၢတ်ႈမႂ်ႇ 2 ဢၼ်ၼႂ်း Video Tools — ဢၼ်ၼိုင်ႈလႅၵ်ႈၵူၼ်းတင်းတူဝ်၊ ဢၼ်ၼိုင်ႈလႅၵ်ႈၼႃႈၵူၺ်း။ ဝီဒီရူဝ်ႈ 10 ၸဵၵ်ႇ",kac:"Video Tools hta card nnan 2 — langai gaw masha yawng galai, langai gaw myiman sha galai. Video gaw 10s du hkra",th:"การ์ดใหม่ 2 ใบใน Video Tools — ใบหนึ่งแทนคนทั้งคนในคลิปด้วยคนในรูปของคุณ อีกใบเปลี่ยนแค่ใบหน้า การเคลื่อนกล้อง จังหวะ ฉาก และเสียงเดิมคงไว้ทั้งหมด แตะครั้งเดียวเลือกเครื่องมือและเขียนคำสั่งให้ คลิปยาวได้ถึง 10 วินาที",zh:"Video Tools 新增两张卡片 — 一张把片中的整个人换成你照片里的人，另一张只换脸。镜头运动、节奏、背景与原声全部保留。点一下即可选好工具并写好提示词；视频最长 10 秒",vi:"Hai thẻ mới ở Video Tools — một thẻ thay toàn bộ người trong clip bằng người trong ảnh của bạn, thẻ kia chỉ đổi khuôn mặt. Chuyển động máy quay, nhịp, bối cảnh và âm thanh gốc đều giữ nguyên. Một chạm là chọn công cụ và viết prompt; clip tối đa 10 giây",id:"Dua kartu baru di Video Tools — satu mengganti seluruh orang dalam klip dengan orang di foto Anda, satu lagi hanya wajah. Gerak kamera, tempo, latar, dan suara asli tetap. Sekali tap memilih alat dan menulis prompt; klip maksimal 10 detik",ms:"Dua kad baharu di Video Tools — satu menggantikan keseluruhan orang dalam klip dengan orang dalam foto anda, satu lagi wajah sahaja. Gerakan kamera, rentak, latar dan bunyi asal semuanya kekal. Satu ketikan memilih alat dan menulis gesaan; klip sehingga 10 saat"} },
  { v:"6.0.0", kind:"page", ref:"pgWf",
    t:{my:"ကိုယ့် pose နဲ့ ဓာတ်ပုံအကွက် အတိုင်း ပြန်ရပါပြီ",en:"Your pose and your framing now come back as you shot them",shn:"ၽၢင်ႁၢင်ႈလႄႈ ၶွပ်ႇၶႅပ်း ပွၵ်ႈမႃးမိူၼ်ၵဝ်ႇ",kac:"Na a pose hte frame gaw shawng na zawn bai lu",th:"ท่าโพสและกรอบภาพกลับมาเหมือนที่คุณถ่าย",zh:"你的姿势与构图现在会原样回来",vi:"Dáng và khuôn hình của bạn nay trở lại đúng như lúc chụp",id:"Pose dan komposisimu kini kembali persis seperti saat difoto",ms:"Pose dan komposisi anda kini kembali seperti ketika dirakam"},
    s:{my:"workflow ၆၁ ခုမှာ crop၊ ကင်မရာထောင့်၊ အရွယ်အစား၊ frame ratio အကြောင်း ဘာမှ မပြောထားခဲ့ဘူး — model က မပြောတဲ့အရာကို လွတ်လပ်စွာ ပြောင်းတတ်ပါတယ်။ အခု ၅၁ ခုမှာ သော့ခတ်လိုက်ပါပြီ။ pose တမင်ပြောင်းတဲ့ Pose Match နဲ့ frame အသစ်ဆောက်တဲ့ ၁၀ ခုကတော့ ချန်ထားပါတယ်",en:"Sixty-one workflows said nothing at all about the crop, the camera angle, the subject's scale or the aspect ratio — and a model is free with whatever it is not told. Fifty-one now lock the frame. Pose Match, whose job is to change the pose, and the ten that build a new picture are deliberately left free",shn:"workflow 61 ဢၼ် ဢမ်ႇလၢတ်ႈလွင်ႈ crop လႄႈ ratio — ယၢမ်းလဵဝ် 51 ဢၼ် ဢိုတ်းဝႆႉ",kac:"Workflow 61 gaw crop hte ratio lam n tsun ai — ya gaw 51 hta jum da sai",th:"เวิร์กโฟลว์ 61 รายการไม่เคยพูดถึงการครอป มุมกล้อง ขนาด หรืออัตราส่วนเลย ตอนนี้ 51 รายการล็อกกรอบภาพแล้ว",zh:"六十一个工作流对裁切、机位、主体大小和画面比例只字未提 — 模型对没被告知的事是自由的。现在其中五十一个锁定了画面",vi:"Sáu mươi mốt workflow không hề nói gì về khung cắt, góc máy, tỷ lệ — nay năm mươi mốt cái đã khoá khung hình",id:"Enam puluh satu alur kerja tak menyebut krop, sudut kamera, atau rasio sama sekali — kini lima puluh satu mengunci bingkai",ms:"Enam puluh satu aliran kerja langsung tidak menyebut kropan, sudut kamera atau nisbah — kini lima puluh satu mengunci bingkai"} },
  { v:"6.0.0", kind:"wf", ref:"studio-look-copy",
    t:{my:"Studio Look Copy — မိတ်ကပ်၊ လက်ဝတ်ရတနာ၊ ဆံပင်ပုံစံပါ ကူးလို့ရပါပြီ",en:"Studio Look Copy now copies the makeup, the jewellery and the hairstyle too",shn:"Studio Look Copy ၵေႃႈ ၵူပ်ႉ မဵၵ်ႉၶၢပ်ႈ လႄႈ ၶူဝ်းၶမ်း",kac:"Studio Look Copy gaw makeup hte ja rai ni mung bai la sai",th:"Studio Look Copy คัดลอกเมกอัป เครื่องประดับ และทรงผมได้แล้ว",zh:"Studio Look Copy 现在也能复制妆容、首饰和发型",vi:"Studio Look Copy giờ sao chép cả trang điểm, trang sức và kiểu tóc",id:"Studio Look Copy kini menyalin riasan, perhiasan, dan gaya rambut juga",ms:"Studio Look Copy kini menyalin solekan, barang kemas dan gaya rambut juga"},
    s:{my:"ခလုတ် ၃ ခု အသစ် — မိတ်ကပ် အသေးစိတ်၊ လည်ဆွဲ/နားကပ်/ဆံထိုး စတဲ့ အလှဆင်ပစ္စည်း၊ ဆံပင်ပုံစံ။ အရင်က ဒါတွေကို သော့ခတ်ထားတဲ့ စာကြောင်း ၂ ခုကို ခလုတ်အပေါ် မူတည်အောင် ပြောင်းလိုက်ပါတယ်။ ဝတ်စုံကိုယ်တိုင်၊ မျက်နှာ၊ pose၊ frame ကတော့ သော့ခတ်ထားမြဲ",en:"Three new switches — the makeup in full detail, the jewellery and hair ornaments, and the hairstyle. The two lines that used to freeze all of it now depend on those switches. The garment itself, the face, the pose and the frame stay locked",shn:"ၼဵၼ်မႂ်ႇ 3 ဢၼ် — မဵၵ်ႉၶၢပ်ႈ၊ ၶူဝ်းၶမ်း၊ ၽူၼ်ႁူဝ်။ သိူဝ်ႈလႄႈ ၼႃႈ ဢမ်ႇလႅၵ်ႈ",kac:"Switch nnan 3 — makeup, ja rai, kara hkum. Palawng hte myi man gaw n galai",th:"สวิตช์ใหม่ 3 ตัว — เมกอัปละเอียด เครื่องประดับ และทรงผม ส่วนชุด ใบหน้า ท่าโพส และกรอบภาพยังล็อกไว้",zh:"三个新开关 — 完整妆容、首饰与发饰、发型。原先冻结这些的两行现在随开关而定；衣服本身、脸、姿势和画面仍然锁定",vi:"Ba công tắc mới — trang điểm chi tiết, trang sức và phụ kiện tóc, kiểu tóc. Trang phục, khuôn mặt, dáng và khung hình vẫn khoá",id:"Tiga sakelar baru — riasan detail, perhiasan dan hiasan rambut, serta gaya rambut. Busana, wajah, pose, dan bingkai tetap terkunci",ms:"Tiga suis baharu — solekan terperinci, barang kemas dan hiasan rambut, serta gaya rambut. Busana, wajah, pose dan bingkai kekal terkunci"} },
  { v:"5.99.0", kind:"wf", ref:"derma-skin",
    t:{my:"Derma Skin Pro ရဲ့ ခလုတ်တွေ ပြောတဲ့အတိုင်း အလုပ်လုပ်ပါပြီ",en:"Derma Skin Pro's switches now mean what they say",shn:"ၼဵၼ် Derma Skin Pro ႁဵတ်းမိူၼ်ဢၼ်ဝႃႈ",kac:"Derma Skin Pro switch ni tsun ai hte maren galaw sai",th:"สวิตช์ของ Derma Skin Pro ทำงานตรงตามที่บอกแล้ว",zh:"Derma Skin Pro 的开关现在名副其实",vi:"Các công tắc của Derma Skin Pro giờ đúng như tên gọi",id:"Sakelar Derma Skin Pro kini sesuai dengan namanya",ms:"Suis Derma Skin Pro kini menepati namanya"},
    s:{my:"ခလုတ် ၅ ခုလုံးမှာ ပိတ်ရင် ဘာဖြစ်မလဲ ပြောတဲ့ စာကြောင်း မပါခဲ့ဘူး — အမာရွတ်ဖျောက်ခြင်း ပိတ်ထားရင်တောင် prompt က အသားအရေ ရှင်းနေဖို့ ဆက်တောင်းနေခဲ့တယ်။ ကိုယ်လုံး ပိတ်ရင်လည်း ကိုယ်လုံးကို ဆက်ပြင်နေခဲ့တယ်။ မှဲ့ကိစ္စမှာလည်း prompt နဲ့ AVOID စာရင်း အချင်းချင်း ဆန့်ကျင်နေခဲ့တယ် — ၃ ခုလုံး ပြင်ပြီးပါပြီ",en:"None of the five switches said what OFF meant, so turning blemish healing off still left the request demanding clear skin, and turning body skin off still had the healing line reaching the body. The AVOID list also forbade the mole removal the prompt asked for — all three are fixed",shn:"ၼဵၼ် 5 ဢၼ် ဢမ်ႇမီးၶေႃႈဝႃႈပိၵ်ႉသေပဵၼ်သင် — ယၢမ်းလဵဝ် မႄးယဝ်ႉ",kac:"Switch 5 hta pat yang hpa byin na n tsun ai — ya gaw mai sai",th:"สวิตช์ทั้ง 5 ไม่เคยบอกว่าปิดแล้วเกิดอะไร ปิดลบสิวแล้วคำสั่งยังเรียกร้องผิวใส และปิดผิวกายแล้วยังลบสิวที่ลำตัว รวมถึงรายการ AVOID ที่ห้ามลบไฝซึ่งพรอมต์สั่งให้ลบ — แก้ครบทั้งสามแล้ว",zh:"五个开关都没有说明关闭后会怎样：关掉祛瑕疵，请求仍在要求无瑕肌肤；关掉身体皮肤，祛瑕疵那行仍会处理身体。AVOID 列表还禁止了提示词要求的去痣 — 三处已全部修好",vi:"Cả năm công tắc đều không nói TẮT nghĩa là gì: tắt xoá khuyết điểm mà yêu cầu vẫn đòi da sạch, tắt da cơ thể mà dòng xoá khuyết điểm vẫn chạm tới thân. Danh sách AVOID còn cấm việc xoá nốt ruồi mà prompt yêu cầu — cả ba đã sửa",id:"Kelima sakelar tak menjelaskan arti MATI: mematikan penghapus noda tetap menyisakan permintaan kulit bersih, dan mematikan kulit tubuh tetap membuat baris penghapus noda menjangkau tubuh. Daftar AVOID juga melarang penghapusan tahi lalat yang diminta prompt — ketiganya sudah diperbaiki",ms:"Kelima-lima suis tidak menyatakan maksud MATI: mematikan penghapus cela masih meninggalkan permintaan kulit bersih, dan mematikan kulit badan masih membuatkan baris penghapus cela mencapai badan. Senarai AVOID turut melarang pembuangan tahi lalat yang diminta gesaan — ketiga-tiganya telah dibaiki"} },
  { v:"5.98.0", kind:"wf", ref:"look-highland-indigo",
    t:{my:"ပိုစ့်နဲ့ ဓာတ်ပုံအကွက် မူရင်းအတိုင်း ကျန်ပါပြီ",en:"Your pose and your framing now stay exactly as you shot them",shn:"ၽၢင်ႁၢင်ႈလႄႈ ၶွပ်ႇၶႅပ်း ၵိုတ်းမိူၼ်ၵဝ်ႇ",kac:"Na a pose hte frame gaw shawng na zawn nga na",th:"ท่าโพสและกรอบภาพคงเดิมตามที่ถ่ายแล้ว",zh:"你的姿势与构图现在会原样保留",vi:"Dáng và khuôn hình của bạn nay giữ nguyên như lúc chụp",id:"Pose dan komposisimu kini tetap persis seperti saat difoto",ms:"Pose dan komposisi anda kini kekal seperti ketika dirakam"},
    s:{my:"Look Set ၁၃ ခုလုံးမှာ “ပိုစ့်ကတော့ ပြောင်းတယ်” လို့ ဖတ်လို့ရတဲ့ စာကြောင်းတစ်ကြောင်း ပါနေခဲ့ပြီး အောက်က စည်းကမ်းနဲ့ ကိုယ်တိုင် ဆန့်ကျင်နေတာ — ဖြုတ်လိုက်ပြီး pose၊ camera angle၊ crop၊ frame ratio တွေကို prompt အစမှာကတည်းက သော့ခတ်လိုက်ပါပြီ",en:"All thirteen sets carried one sentence a model could read as “the pose does change”, three lines above a rule saying it must not — it is gone, and pose, camera angle, crop and aspect ratio are now locked in the prompt's opening line",shn:"Look Set 13 ဢၼ်မီးဝႆႉၶေႃႈၼိုင်ႈ ၶတ်းၵၼ်တင်းမၢႆမီႈတႂ်ႈ — ထွၼ်ဢွၵ်ႇယဝ်ႉ",kac:"Look Set 13 ting hta tsun ga langai npawt hte shada n hkrum ai nga ai — shaw kau sai",th:"ทั้ง 13 เซ็ตเคยมีประโยคที่โมเดลอ่านได้ว่า “ท่าเปลี่ยนได้” ซึ่งขัดกับกฎด้านล่าง — ตอนนี้ลบออกแล้ว และล็อกท่า มุมกล้อง การครอป และอัตราส่วนไว้ตั้งแต่บรรทัดแรก",zh:"十三组套装都带着一句可被读成「姿势是会变的」的话，而三行之下的规则却说不可以 — 这句已删除，姿势、机位、裁切与画面比例改在提示词第一行就锁定",vi:"Cả mười ba bộ đều mang một câu có thể bị đọc thành “dáng thì có đổi”, ngay trên quy tắc nói không được — câu đó đã bỏ, và dáng, góc máy, khung cắt, tỷ lệ nay khoá ngay dòng đầu",id:"Ketiga belas set memuat satu kalimat yang bisa dibaca sebagai “pose memang berubah”, tepat di atas aturan yang melarangnya — kalimat itu dihapus, dan pose, sudut kamera, krop serta rasio kini dikunci di baris pertama",ms:"Kesemua tiga belas set membawa satu ayat yang boleh dibaca sebagai “pose memang berubah”, tepat di atas peraturan yang melarangnya — ayat itu dibuang, dan pose, sudut kamera, kropan serta nisbah kini dikunci pada baris pertama"} },
  { v:"5.98.0", kind:"page", ref:"pgCreate",
    t:{my:"Ratio = Auto ဆိုရင် ကိုယ့်ပုံရဲ့ ပုံသဏ္ဌာန်အတိုင်း ထွက်ပါပြီ",en:"Ratio on Auto now means the shape your photo already is",shn:"Ratio Auto ၸိုင် ပဵၼ်ႁၢင်ႈၶႅပ်းႁၢင်ႈၸဝ်ႈၵဝ်ႇ",kac:"Ratio Auto gaw na a sumla a hkum hte maren",th:"Ratio = Auto ตอนนี้หมายถึงสัดส่วนเดิมของภาพคุณ",zh:"比例设为 Auto，现在就是你照片本来的形状",vi:"Ratio để Auto giờ chính là hình dạng vốn có của ảnh bạn",id:"Ratio pada Auto kini berarti bentuk asli fotomu",ms:"Nisbah pada Auto kini bermaksud bentuk asal foto anda"},
    s:{my:"model ၆ ခုမှာ Auto က တကယ်တော့ 1:1 (စတုရန်း) ပို့နေခဲ့တာ — ဒါကြောင့် prompt က ဘာပဲပြောပြော ဓာတ်ပုံက စတုရန်း ပြန်လာတာ။ အခု မူရင်းပုံကို တိုင်းပြီး အနီးစပ်ဆုံး ratio ကို ပို့ပါတယ်",en:"On six models Auto was really sending 1:1 — square — so a portrait came back square no matter what the prompt said. Your photo is now measured and the nearest supported ratio is sent instead",shn:"model 6 ဢၼ် Auto သူင်ႇ 1:1 — ယၢမ်းလဵဝ် တႅၵ်ႈၶႅပ်းႁၢင်ႈသေ သူင်ႇဢၼ်ႁဵတ်းၸမ်",kac:"Model 6 hta Auto gaw 1:1 sa ai — ya gaw sumla hpe shadawn nna ni htum ai ratio sa na",th:"บนโมเดล 6 ตัว Auto ส่งเป็น 1:1 (จัตุรัส) จริง ๆ ภาพจึงกลับมาเป็นจัตุรัสไม่ว่าพรอมต์จะบอกอะไร ตอนนี้วัดจากภาพต้นฉบับแล้วส่งอัตราส่วนที่ใกล้ที่สุด",zh:"在六个模型上，Auto 实际发送的是 1:1 正方形，所以无论提示词怎么写，人像都会变成方图。现在会测量你的原图并发送最接近的受支持比例",vi:"Trên sáu model, Auto thực chất gửi 1:1 — vuông — nên ảnh chân dung trả về hình vuông dù prompt viết gì. Nay ảnh của bạn được đo và gửi tỷ lệ gần nhất được hỗ trợ",id:"Pada enam model, Auto sebenarnya mengirim 1:1 — persegi — sehingga potret kembali persegi apa pun isi prompt. Kini fotomu diukur dan rasio terdekat yang didukung dikirim",ms:"Pada enam model, Auto sebenarnya menghantar 1:1 — segi empat sama — jadi potret kembali sebagai segi empat walau apa pun gesaannya. Kini foto anda diukur dan nisbah disokong yang terdekat dihantar"} },
  { v:"5.97.0", kind:"wf", ref:"look-golden-grecian",
    t:{my:"Look Set တွေမှာ အဖြူရောင် မီးလုံးကြီး မပါတော့ပါ",en:"The white light blob is gone from the Look Sets",shn:"ၼႂ်း Look Set ဢမ်ႇမီး လွင်ႈလႅင်းၽိူၵ်ႇလူင်ယဝ်ႉ",kac:"Look Set ni hta nsam hpraw kaba nlu mat sai",th:"ดวงแสงขาวใหญ่หายไปจากเซ็ตลุคแล้ว",zh:"造型套装里的大白光斑没有了",vi:"Vệt sáng trắng lớn đã biến khỏi các Look Set",id:"Bercak cahaya putih besar hilang dari Look Set",ms:"Tompok cahaya putih besar hilang daripada Look Set"},
    s:{my:"ဓာတ်ပုံထောင့်မှာ ဝင်လာတတ်တဲ့ အလင်းဖြူပွင့်ကြီးကို ၁၃ ခုလုံးမှာ ပိတ်လိုက်ပါပြီ — မီးအိမ်၊ softbox၊ flare မပေါ်တော့ဘဲ အလင်းအဆုံးနေရာမှာလည်း အသေးစိတ် ကျန်ပါတယ်",en:"A blown white glow used to bleed into the corner of the frame — all thirteen sets now forbid it, so no lamp, softbox or flare shows and even the brightest area keeps its detail",shn:"လႅင်းၽိူၵ်ႇလူင် ဢၼ်ၶဝ်ႈမႃးတီႈၸဵင်ႇ ၶႅပ်းႁၢင်ႈ — ယၢမ်းလဵဝ် ႁၢမ်ႈဝႆႉတင်း 13 ၸုမ်း",kac:"Sumla n-gang de nsam hpraw shang wa ai hpe ya gaw 13 ting hta n hkap la sai",th:"แสงขาวจ้าที่เคยเลียเข้ามาที่มุมภาพ ถูกห้ามในทั้ง 13 เซ็ตแล้ว ไม่มีโคมไฟ ซอฟต์บ็อกซ์ หรือแฟลร์ และส่วนที่สว่างที่สุดยังคงรายละเอียด",zh:"过去会从画面角落渗入的死白光晕，现在十三组套装全部禁止 — 不再出现灯具、柔光箱或炫光，最亮处也保留细节",vi:"Vệt sáng trắng cháy từng loang vào góc khung hình — cả mười ba bộ nay đều cấm, không lộ đèn, softbox hay flare và vùng sáng nhất vẫn giữ chi tiết",id:"Cahaya putih menyilaukan yang dulu merembes ke sudut bingkai kini dilarang di ketiga belas set — tak ada lampu, softbox atau flare, dan area paling terang tetap berdetail",ms:"Cahaya putih terlebih dedah yang dahulu meresap ke sudut bingkai kini dilarang pada kesemua tiga belas set — tiada lampu, softbox atau suar, dan kawasan paling cerah kekal berbutir"} },
  { v:"5.97.0", kind:"page", ref:"pgPath",
    t:{my:"တစ်စီးရီးလုံး engine တစ်ခုတည်းကနေ ထွက်ပါပြီ",en:"One series now comes out of one engine",shn:"ၸုတ်းလဵဝ် ဢွၵ်ႇမႃးတီႈ engine လဵဝ်",kac:"Series langai gaw engine langai kaw na pru wa sai",th:"หนึ่งชุดภาพออกมาจากเอนจินเดียว",zh:"一整组照片现在出自同一个引擎",vi:"Một loạt ảnh giờ ra từ cùng một engine",id:"Satu seri kini keluar dari satu engine",ms:"Satu siri kini terhasil daripada satu enjin"},
    s:{my:"ဓာတ်ပုံ ၁၀၀ လုပ်နေရင်း model ပြောင်းသွားရင် အသွင်အပြင် မတူတော့ဘူး — အခု စတင်ချိန်က model ကို အဆုံးထိ ကိုင်ထားပြီး တစ်ခုခု တခြား engine ကနေ ထွက်ခဲ့ရင်လည်း အစီရင်ခံပါတယ်",en:"A model swapped halfway through a hundred photos used to leave them looking unalike — the run now holds the model it started with, and reports it if anything still came from another",shn:"ႁဵတ်းၶႅပ်းႁၢင်ႈ 100 သေ လႅၵ်ႈ model ၵၢင်တၢင်း ၸိုင် ဢမ်ႇမိူၼ်ၵၼ် — ယၢမ်းလဵဝ် ၵမ် model ဢွၼ်တၢင်းဝႆႉတေႃႇသုတ်း",kac:"Sumla 100 galaw nga yang ka-ang hta model galai ai majaw n bung mat ai — ya gaw nnan hpang ai model hpe hpang jahtum du hkra jum da na",th:"การเปลี่ยนโมเดลกลางคันระหว่างทำ 100 ภาพเคยทำให้ภาพไม่เข้ากัน — ตอนนี้จะยึดโมเดลที่เริ่มไว้จนจบ และรายงานถ้ามีภาพใดมาจากเอนจินอื่น",zh:"一百张照片做到一半换了模型，成片就不像同一组 — 现在整轮固定使用开始时的模型，若仍有出自其他引擎的也会如实报告",vi:"Đổi model giữa chừng khi làm một trăm ảnh từng khiến chúng không giống nhau — nay cả lượt giữ nguyên model lúc bắt đầu, và báo lại nếu vẫn có ảnh đến từ engine khác",id:"Model yang berganti di tengah seratus foto dulu membuat hasilnya tak senada — kini satu putaran memegang model saat dimulai, dan melaporkannya bila ada yang tetap dari engine lain",ms:"Model yang bertukar di pertengahan seratus foto dahulu menjadikan hasilnya tidak sepadan — kini satu pusingan mengekalkan model ketika dimulakan, dan melaporkannya jika ada yang masih daripada enjin lain"} },
  { v:"5.96.0", kind:"wf", ref:"look-temple-lightfall",
    t:{my:"Look Set တွေ ပိုတိုပြီး ပိုပြည့်စုံလာပါပြီ",en:"The Look Sets got shorter, and arrive more complete",shn:"Look Set ပွင်ႇထႅမ်လိူဝ်သေ ပွတ်းလိူဝ်",kac:"Look Set ni kadun nna grau hkum wa sai",th:"เซ็ตลุคสั้นลงและส่งถึงครบขึ้น",zh:"造型套装更短了，也更完整地送达",vi:"Các Look Set ngắn hơn và đến nơi đầy đủ hơn",id:"Look Set jadi lebih ringkas dan sampai lebih utuh",ms:"Look Set menjadi lebih ringkas dan sampai lebih lengkap"},
    s:{my:"prompt ရဲ့ ၆၂% က ၁၃ ခုလုံးမှာ ထပ်နေတဲ့ စာသားပါ — အဓိပ္ပာယ် မလျော့ဘဲ စာလုံး ၉၀၀ လျှော့လိုက်လို့ model ပိုများများမှာ set အပြည့် ရောက်ပါပြီ",en:"62% of each prompt was text repeated in all thirteen — 900 characters lighter with nothing dropped, so more models now receive the whole set",shn:"prompt 62% ပဵၼ်ၶေႃႈထပ်း — မွၵ်ႈ 900 တူဝ်ဢေႇလူင်း",kac:"Prompt 62% gaw bai tsun ai re — 900 chars kadun sai",th:"62% ของพรอมต์เป็นข้อความซ้ำ — เบาลง 900 ตัวอักษรโดยไม่เสียความหมาย",zh:"每条提示词有 62% 是十三组共用的重复文字 — 精简 900 字符而不丢失任何规则",vi:"62% mỗi prompt là chữ lặp lại ở cả mười ba — nhẹ đi 900 ký tự mà không mất quy tắc nào",id:"62% tiap prompt adalah teks berulang di ketiga belasnya — 900 karakter lebih ringan tanpa kehilangan aturan",ms:"62% setiap gesaan ialah teks berulang pada kesemua tiga belas — 900 aksara lebih ringan tanpa kehilangan sebarang peraturan"} },
  { v:"5.95.0", kind:"page", ref:"pgWf",
    t:{my:"Model ပြောင်းရင် prompt အလိုအလျောက် လိုက်ညှိပါပြီ",en:"The prompt now fits itself to the model you pick",shn:"လႅၵ်ႈ model ၸိုင် prompt ငၢႆႈငၢႆႈလိုၵ်ႉ",kac:"Model galai yang prompt hkrak hkra galai sai",th:"พรอมต์ปรับตามโมเดลที่เลือกอัตโนมัติแล้ว",zh:"提示词现在会自动适配你选的模型",vi:"Prompt giờ tự khớp với model bạn chọn",id:"Prompt kini menyesuaikan diri dengan model yang dipilih",ms:"Gesaan kini menyesuaikan diri dengan model yang dipilih"},
    s:{my:"prompt ရှည်ရင် စာကြောင်းအလယ် ဖြတ်တာမျိုး မလုပ်တော့ဘဲ မလိုအပ်တဲ့ အပိုင်းလိုက် ဖြုတ်ပါတယ် — မဝင်နိုင်ရင်တော့ အပြည့်လက်ခံနိုင်တဲ့ model ဆီ ပြောင်းပြီး ဘာကြောင့်လဲ ပြောပြပါတယ်",en:"A long workflow now loses whole sections it can spare instead of stopping mid-sentence — and when even that won't fit, the run moves to a model that can take all of it, and says why",shn:"prompt ယၢဝ်း ၸိုင် တတ်ႉၵၢင်ဝႃႇၵျႃႇဢမ်ႇမီး — ဢမ်ႇမႅၼ်ႈၸိုင် လႅၵ်ႈ model",kac:"Prompt galu yang ka-ang hta n kadun sai — n hkrak yang model galai na",th:"เวิร์กโฟลว์ยาวจะตัดทั้งส่วนแทนการตัดกลางประโยค — ถ้ายังไม่พอจะย้ายไปโมเดลที่รับได้ทั้งหมด",zh:"较长的工作流现在整段舍弃而不是从句子中间截断 — 若仍放不下，会切换到能完整接受的模型",vi:"Workflow dài giờ bỏ trọn từng phần thay vì cắt giữa câu — nếu vẫn không vừa, sẽ chuyển sang model nhận được toàn bộ",id:"Alur panjang kini melepas bagian utuh alih-alih terpotong di tengah kalimat — bila masih tak muat, dipindah ke model yang bisa menerima seluruhnya",ms:"Aliran panjang kini melepaskan bahagian penuh dan bukan terpotong di tengah ayat — jika masih tidak muat, ia bertukar ke model yang boleh menerima kesemuanya"} },
  { v:"5.94.0", kind:"page", ref:"pgCreate",
    t:{my:"ရွေးလိုက်တဲ့ ratio နဲ့ size အမှန်ထွက်ပါပြီ",en:"The ratio and size you pick now really come out",shn:"ratio လႄႈ size ဢၼ်လိူၵ်ႈ ဢွၵ်ႇမႃးတႄႉယဝ်ႉ",kac:"Lata ai ratio hte size teng sha pru wa sai",th:"อัตราส่วนและขนาดที่เลือกออกมาจริงแล้ว",zh:"你选择的比例和尺寸现在真的会生效",vi:"Tỷ lệ và kích thước bạn chọn giờ thực sự ra đúng",id:"Rasio dan ukuran yang kamu pilih kini benar-benar diterapkan",ms:"Nisbah dan saiz yang anda pilih kini benar-benar digunakan"},
    s:{my:"Seedream v4/v4.5 မှာ ratio ရွေးလို့ရပေမဲ့ တကယ်မပါခဲ့ဘူး — အခု မလိုတဲ့ခလုတ်ကို ဖျောက်ထားပါပြီ။ Size က ratio ပေါ်မူတည်တဲ့ model တွေမှာလည်း ကြိုပြောပါပြီ",en:"Seedream v4/v4.5 let you pick a ratio that was never sent — that control is now hidden. And where size comes from the ratio, the app says so before you spend a credit",shn:"Seedream v4/v4.5 လိူၵ်ႈ ratio လႆႈသေတႃႉ ဢမ်ႇသူင်ႇ — ယၢမ်းလဵဝ် ဢိုတ်းဝႆႉ",kac:"Seedream v4/v4.5 hta ratio lata mai tim n sa ai — ya gaw makoi da sai",th:"Seedream v4/v4.5 เคยให้เลือกอัตราส่วนที่ไม่เคยถูกส่ง — ตอนนี้ซ่อนแล้ว",zh:"Seedream v4/v4.5 曾允许选择从未被发送的比例 — 该控件现已隐藏",vi:"Seedream v4/v4.5 từng cho chọn tỷ lệ không bao giờ được gửi — nay đã ẩn",id:"Seedream v4/v4.5 dulu membiarkan memilih rasio yang tak pernah dikirim — kini disembunyikan",ms:"Seedream v4/v4.5 dahulu membenarkan pilihan nisbah yang tidak pernah dihantar — kini disembunyikan"} },
  { v:"5.93.0", kind:"page", ref:"pgHome",
    t:{my:"ဝင်လို့မရရင် ဘာကြောင့်လဲ ရှင်းရှင်းပြောပါပြီ",en:"When sign-in fails, it now tells you why",shn:"ၶဝ်ႈဢမ်ႇလႆႈၸိုင် ၸႅင်ႈလႅင်းဝႃႈသင်",kac:"Shang n mai yang hpa majaw re tsun sai",th:"ถ้าเข้าสู่ระบบไม่ได้ ตอนนี้บอกสาเหตุแล้ว",zh:"登录失败时，现在会说明原因",vi:"Khi đăng nhập lỗi, giờ sẽ nói rõ vì sao",id:"Saat gagal masuk, kini dijelaskan sebabnya",ms:"Apabila log masuk gagal, kini ia menyatakan sebabnya"},
    s:{my:"ခဏစောင့်ရမလား၊ စကားဝှက် မှားနေလား၊ အင်တာနက် ပြဿနာလား — အခု ခွဲပြီး ပြောပါတယ်။ ကီးဘုတ်က Go ခလုတ်နဲ့လည်း ဝင်လို့ရပါပြီ",en:"Whether to wait, fix your password, or check your connection — the app now says which. And the keyboard's Go key signs you in",shn:"ပႂ်ႉၼႃႇ၊ ၶေႃႈလပ်ႉၽိတ်း၊ ဢိၼ်ႇတိူဝ်ႇၼႅတ်ႉ — ၸႅင်ႈလႅင်းယဝ်ႉ။ ၼဵၼ် Go ၵေႃႈၶဝ်ႈလႆႈ",kac:"La ra na, password shut ai, sh'ning internet — ya tsun dan sai. Keyboard Go mung shang mai sai",th:"ต้องรอ ต้องแก้รหัสผ่าน หรือปัญหาเน็ต — ตอนนี้บอกชัด และปุ่ม Go บนคีย์บอร์ดก็เข้าสู่ระบบได้",zh:"是要等待、密码错误，还是网络问题 — 现在会分清楚。键盘上的 Go 键也能登录",vi:"Cần đợi, sai mật khẩu, hay lỗi mạng — giờ ứng dụng nói rõ. Phím Go trên bàn phím cũng đăng nhập được",id:"Harus menunggu, kata sandi salah, atau masalah koneksi — kini dijelaskan. Tombol Go di keyboard juga bisa masuk",ms:"Perlu menunggu, kata laluan salah, atau masalah sambungan — kini dinyatakan. Kekunci Go pada papan kekunci juga boleh log masuk"} },
  /* v5.92.0 points at the Workflows page, not at a Look Set card: the news
     is a change to every set's switches, so the shelf is the honest
     destination. (It was once also a workaround — two unread entries could
     not both lead one category. Since 5.97.0 they can: the render sorts
     every unread card forward and verify_whats_new E2 checks the whole
     leading run, so an entry may now name whatever it actually changed.) */
  { v:"5.92.0", kind:"page", ref:"pgWf",
    t:{my:"ခလုတ်ပိတ်ရင် ဘာဖြစ်မလဲ ရှင်းပါပြီ",en:"Every switch now says what OFF means",shn:"ပိၵ်ႉသေ ပဵၼ်သင် ၸႅင်ႈလႅင်းယဝ်ႉ",kac:"Switch pat yang hpa byin na chye sai",th:"ปิดสวิตช์แล้วเกิดอะไร ชัดเจนแล้ว",zh:"每个开关都说明了关闭时的效果",vi:"Mỗi công tắc giờ nói rõ TẮT nghĩa là gì",id:"Setiap sakelar kini menjelaskan arti MATI",ms:"Setiap suis kini menyatakan maksud MATI"},
    s:{my:"Look Set မှာ ဝတ်စုံ+မိတ်ကပ် ပိတ်ရင် ကိုယ့်အဝတ်အစား အတိအကျ ကျန်မယ် — prompt ရှည်ရင်လည်း model တိုင်းက အလုပ်အဓိကကို အရင်ရပါပြီ",en:"Turn Wardrobe+makeup off on a Look Set and your own outfit stays exactly as shot — and on models that cut long prompts, the task now arrives first",shn:"ပိၵ်ႉၶူဝ်းၼုင်ႈ+မဵၵ်ႉၶၢပ်ႈ ၼႂ်း Look Set သေ ၶူဝ်းၼုင်ႈတူဝ်ၵဝ်ႇ ၵိုတ်းဝႆႉမိူၼ်ၵဝ်ႇ — model ဢၼ်တတ်ႉ prompt ၵေႃႈ လႆႈၵၢၼ်ၼႃႈဢွၼ်တၢင်း",kac:"Look Set hta Palawng+makeup pat yang na palawng nan hte raw nga na — prompt kadun ai model ni mung bungli hpe shawng la na",th:"ปิดชุดและแต่งหน้าใน Look Set แล้วชุดของคุณจะคงเดิมทุกอย่าง — และโมเดลที่ตัด prompt ยาวจะได้รับงานหลักก่อน",zh:"在造型套装中关闭服装与妆容，你自己的穿着将原样保留 — 会截断长提示词的模型现在也会先收到任务本身",vi:"Tắt Trang phục+trang điểm trong Look Set thì trang phục của bạn giữ nguyên như ảnh chụp — và các model cắt prompt dài giờ nhận phần việc chính trước",id:"Matikan Busana+riasan di Look Set dan pakaianmu tetap persis seperti difoto — dan model yang memotong prompt panjang kini menerima tugas utamanya lebih dulu",ms:"Matikan Busana+solekan dalam Look Set dan pakaian anda kekal seperti difoto — dan model yang memotong prompt panjang kini menerima tugas utama dahulu"} },
  { v:"5.91.0", kind:"wf", ref:"look-golden-grecian",
    t:{my:"Look Set ကတ်အသစ် ၁၃ ခု",en:"Thirteen new Look Sets",shn:"ၸုမ်းလင်ႇသဵၼ်ႈမႂ်ႇ 13",kac:"Look Set nnan 13",th:"13 เซ็ตลุคใหม่",zh:"13 组全新造型套装",vi:"13 bộ Look Set mới",id:"13 Look Set baru",ms:"13 Look Set baharu"},
    s:{my:"နောက်ခံအရောင်၊ အလင်း၊ အရောင်ချိန်၊ ဝတ်စုံ အတိအကျ တစ်ပုံစံတည်း — ပုံ ၁၀၀ လုပ်လည်း တစ်ရိုက်တည်းလို။ ဝတ်စုံ+မိတ်ကပ် နဲ့ အသားရောင် ခလုတ် သီးသန့်ပါတယ်",en:"Backdrop, light, grade and wardrobe fixed on every photo, so a hundred frames read as one shoot — with their own wardrobe+makeup and skin-tone switches",shn:"သီလင်၊ ၾႆး၊ လၢႆးသီ၊ ၶူဝ်းၼုင်ႈ မိူၼ်ၵၼ်ၵူႊၶႅပ်း",kac:"Shakum, nhtoi, grade, palawng yawng maren",th:"ฉาก แสง เกรดสี และชุด เหมือนกันทุกภาพ",zh:"背景、布光、调色与服装每张一致",vi:"Phông, ánh sáng, màu và trang phục giống nhau mọi ảnh",id:"Latar, cahaya, grading dan busana sama di setiap foto",ms:"Latar, cahaya, gred dan busana sama pada setiap foto"} },
  { v:"5.90.0", kind:"page", ref:"pgWf",
    t:{my:"အသစ်ထွက်တာတွေ ချက်ချင်းသိရပါပြီ",en:"You'll see what's new, straight away",shn:"တေႁၼ်ၶိူင်ႈမႂ်ႇတင်းသဵင်ႈ",kac:"Nnan ai ni hpe mu na",th:"เห็นของใหม่ได้ทันที",zh:"新功能一眼就看到",vi:"Thấy ngay cái mới",id:"Langsung lihat yang baru",ms:"Terus nampak yang baharu"},
    s:{my:"ကတ်အသစ်တွေမှာ ရွှေရောင် NEW တံဆိပ် တပ်ထားပြီး အပေါ်ဆုံးမှာ ပြပါတယ် — နှိပ်ပြီး ချက်ချင်းစမ်းလို့ရပါတယ်",en:"New cards wear a gold NEW mark and sit at the top of their group — tap to try one now",shn:"ၶႅပ်းမႂ်ႇမီးမၢႆ NEW သီၶမ်း",kac:"Nnan ai card ni gold NEW lam tsun",th:"การ์ดใหม่มีป้าย NEW สีทองและอยู่บนสุด",zh:"新卡片带金色 NEW 标记并排在最前",vi:"Thẻ mới có nhãn NEW vàng và nằm trên cùng",id:"Kartu baru bertanda NEW emas dan ada di paling atas",ms:"Kad baharu bertanda NEW emas di bahagian atas"} },
  { v:"5.89.0", kind:"page", ref:"pgVideo",
    t:{my:"Video model အသစ် ၁၂ ခု",en:"Twelve new video models",shn:"ဝီးတီးဢူဝ်း model မႂ်ႇ 12",kac:"Video model nnan 12",th:"โมเดลวิดีโอใหม่ 12 ตัว",zh:"12 个新视频模型",vi:"12 mô hình video mới",id:"12 model video baru",ms:"12 model video baharu"},
    s:{my:"MiniMax H3 Max, H3 Context-IR (အသံပါ), Gemini Omni 1.1 Flash နဲ့ 768P ကို 2K ပြန်ထုတ်တဲ့ tool တွေ",en:"MiniMax H3 Max, H3 Context-IR (with sound), Gemini Omni 1.1 Flash, and 768P→2K regeneration tools",shn:"MiniMax H3 Max, Context-IR, Gemini Omni 1.1",kac:"MiniMax H3 Max, Context-IR, Gemini Omni 1.1",th:"MiniMax H3 Max, Context-IR (มีเสียง), Gemini Omni 1.1",zh:"MiniMax H3 Max、Context-IR（带声音）、Gemini Omni 1.1",vi:"MiniMax H3 Max, Context-IR (có tiếng), Gemini Omni 1.1",id:"MiniMax H3 Max, Context-IR (bersuara), Gemini Omni 1.1",ms:"MiniMax H3 Max, Context-IR (berbunyi), Gemini Omni 1.1"} },
  { v:"5.87.0", kind:"wf", ref:"studio-look-copy",
    t:{my:"Studio Look Copy",en:"Studio Look Copy",shn:"Studio Look Copy",kac:"Studio Look Copy",th:"Studio Look Copy",zh:"Studio Look Copy",vi:"Studio Look Copy",id:"Studio Look Copy",ms:"Studio Look Copy"},
    s:{my:"နမူနာပုံတစ်ပုံရဲ့ အရောင်၊ အလင်း၊ အသားရေ၊ scene အကုန်လုံးကို ကိုယ့်ပုံဆီ ကူးယူပေးတယ် — ပုံရာနဲ့ချီ တစ်ပုံစံတည်း",en:"Copies one reference photo's whole scene, colour, light and skin into your photo — the same look across a hundred frames",shn:"လၢႆးသီ လႄႈ ၾႆး ၶွင်ၶႅပ်းၼမူႇ",kac:"Reference sumla a nsam hte nhtoi",th:"คัดลอกโทนสี แสง ผิว ทั้งฉากจากรูปอ้างอิง",zh:"把参考照片的场景、色彩、光线和肤质整套复制到你的照片",vi:"Sao chép toàn bộ bối cảnh, màu, ánh sáng và da từ ảnh mẫu",id:"Menyalin seluruh suasana, warna, cahaya dan kulit dari foto acuan",ms:"Menyalin seluruh suasana, warna, cahaya dan kulit dari foto rujukan"} },
  { v:"5.86.0", kind:"page", ref:"pgGallery",
    t:{my:"ရလဒ်တွေ အလိုအလျောက် သိမ်းထားပြီ",en:"Your results are kept automatically",shn:"ၽွၼ်းလႆႈ လႆႈသိမ်းဝႆႉ",kac:"Nan a lam ni hpe makawp",th:"ผลงานถูกเก็บอัตโนมัติ",zh:"生成结果会自动保存",vi:"Kết quả được lưu tự động",id:"Hasil tersimpan otomatis",ms:"Hasil disimpan automatik"},
    s:{my:"Tab ပိတ်သွားရင်တောင် ရလဒ်တွေ Gallery ထဲမှာ ကျန်နေမယ် — ကိုယ်တိုင်ဖျက်မှ ပျောက်မယ်",en:"Close the tab and the results are still in your Gallery — they go only when you delete them",shn:"ပိၵ်း tab သေတႃႉ ၽွၼ်းလႆႈယင်းမီး",kac:"Tab la kau tim Gallery hta naw nga",th:"ปิดแท็บแล้วผลงานยังอยู่ในแกลเลอรี",zh:"关掉分页，结果仍在图库里",vi:"Đóng tab, kết quả vẫn còn trong Thư viện",id:"Tutup tab, hasil tetap ada di Galeri",ms:"Tutup tab, hasil kekal dalam Galeri"} }
];

var API = { LIST: WHATS_NEW,
  key: function (e) { return e.v + "|" + e.ref; },
  /* the panel keeps its own read-record: the same student on the same
     machine, but UXP storage is not the browser's localStorage, so a card
     read on the phone stays new in Photoshop and vice versa. That is the
     honest behaviour — neither surface can see the other's storage. */
  SEEN_KEY: "hnk_new_seen" };

if (typeof module !== "undefined" && module.exports) module.exports = API;
else { globalThis.HNK = globalThis.HNK || {}; globalThis.HNK.whatsNew = API; }
})();
