#!/usr/bin/env node
"use strict";
/* Build panel/js/hnk_pstyle.js + the Portrait Style rules in panel/styles.css from the web app —
   the Portrait Style page (6.142.0) is ONE module that runs on both surfaces, the Imagine pattern.

   The app's index.html carries the module between two comment markers, PSTYLE_MODULE and
   /PSTYLE_MODULE (the three-step wizard: your photo · style · result, drawn into a root element,
   asking a host adapter for strings, icons, the studio's template art, files, the camera, the
   RunningHub call, the Gallery, the export and the print). The panel gets that block byte for
   byte, with the app's data line (window.HNK_PSTYLE, loaded by the shell from data/pstyle.js)
   replaced by the same JSON inlined, plus one line that hangs it on globalThis.HNK. Its CSS is the
   app's block between the PSTYLE_CSS markers with the app's colour tokens renamed to the panel's
   and the page id renamed, run through uxpSafeCss (no gap, no pointer-events on UXP).

   The building-block references are the Imagine tools' template thumbnails, which build_panel_imagine
   already copies to panel/icons/imagine/th; the occasion sets (6.143.0) are the studio's own pictures under
   docs/app/lib/wf/pstyle/th, copied here to panel/icons/pstyle/th.

   Idempotent: running it on a clean tree changes nothing.
   Usage: node tools/build_panel_pstyle.js
   test/verify_pstyle_6142.js re-runs this and fails on drift. */
const fs = require("fs");
const path = require("path");
const ROOT = path.join(__dirname, "..");
const APP = path.join(ROOT, "docs", "app", "index.html");
const OUT_JS = path.join(ROOT, "panel", "js", "hnk_pstyle.js");
const OUT_CSS = path.join(ROOT, "panel", "styles.css");
const ART_SRC = path.join(ROOT, "docs", "app", "lib", "wf", "pstyle", "th");   /* 6.143.0 — the studio's own occasion sets */
const ART_DST = path.join(ROOT, "panel", "icons", "pstyle", "th");

const M0 = "/* ---- PSTYLE_MODULE ---- */", M1 = "/* ---- /PSTYLE_MODULE ---- */";
const C0 = "/* ---- PSTYLE_CSS ---- */", C1 = "/* ---- /PSTYLE_CSS ---- */";

function between(src, a, b, what) {
  const i = src.indexOf(a); if (i < 0) throw new Error(what + ": start marker missing " + a);
  const j = src.indexOf(b, i); if (j < 0) throw new Error(what + ": end marker missing " + b);
  if (src.indexOf(a, i + 1) >= 0) throw new Error(what + ": start marker appears twice");
  return src.slice(i, j + b.length);
}
const TOKENS = [["var(--gold-hi)", "var(--accent-h)"], ["var(--gold)", "var(--accent)"], ["var(--cream)", "var(--text)"], ["var(--ink)", "var(--bg)"], ["var(--muted)", "var(--muted)"]];
const { uxpSafeCss } = require("./lib/uxp_safe_css.js");
const { uxpSafeCode } = require("./lib/uxp_safe_text.js");
const A = require("./lib/app-data.js");
function panelCss(appCss) {
  let s = appCss;
  TOKENS.forEach(function (p) { s = s.split(p[0]).join(p[1]); });
  s = s.split("#pgPStyle").join("#pagePStyle");
  return uxpSafeCss(s, "build_panel_pstyle (the PSTYLE_CSS block lifted from docs/app/index.html)");
}
let DRY = false;
function writeIfChanged(file, content) {
  const cur = fs.existsSync(file) ? fs.readFileSync(file) : null;
  const buf = Buffer.isBuffer(content) ? content : Buffer.from(content, "utf8");
  if (cur && cur.equals(buf)) return false;
  if (DRY) return true;
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, buf);
  return true;
}
function build(opts) {
  DRY = !!(opts && opts.dry);
  const app = fs.readFileSync(APP, "utf8");
  const DATA_LINE = "var PSTYLE_DATA = window.HNK_PSTYLE;";
  const mod0 = between(app, M0, M1, "module");
  if (mod0.split(DATA_LINE).length !== 2) throw new Error("build_panel_pstyle: the PSTYLE module must read its tables with exactly one `" + DATA_LINE + "`");
  const mod = mod0.replace(DATA_LINE, "var PSTYLE_DATA = " + A.pstyleText() + ";");
  const js = "/* GENERATED by tools/build_panel_pstyle.js from docs/app/index.html — do not edit by hand.\n" +
    "   The web app's Portrait Style module (6.142.0), byte for byte: PSTYLE_DATA (the words in nine\n" +
    "   languages, the reference groups, the toggles and the prompt frame — inlined from\n" +
    "   docs/app/data/pstyle.js, which the web app loads by <script src>) and the PSTYLE UI. main.js\n" +
    "   hands it the panel's host adapter (pstyleHost) and a root element; nothing here knows it is\n" +
    "   inside Photoshop. */\n" +
    mod + "\n" +
    "globalThis.HNK = globalThis.HNK || {};\n" +
    "globalThis.HNK.pstyle = PSTYLE;\n" +
    "globalThis.HNK.pstyleData = PSTYLE_DATA;\n";
  const changed = [];
  if (writeIfChanged(OUT_JS, uxpSafeCode(js, "build_panel_pstyle (the PSTYLE module lifted from docs/app/index.html)"))) changed.push("panel/js/hnk_pstyle.js");
  const css = panelCss(between(app, C0, C1, "css"));
  let cur = fs.readFileSync(OUT_CSS, "utf8");
  let next;
  if (cur.indexOf(C0) >= 0) next = cur.replace(between(cur, C0, C1, "panel css"), css);
  else next = cur.replace(/\s*$/, "\n\n") + css + "\n";
  if (next !== cur) { if (!DRY) fs.writeFileSync(OUT_CSS, next); changed.push("panel/styles.css"); }
  /* art: every jpg under docs/app/lib/wf/pstyle/th — the same pictures on both surfaces */
  if (fs.existsSync(ART_SRC)) fs.readdirSync(ART_SRC).forEach(function (f) {
    if (!/\.(jpe?g|png|webp)$/i.test(f)) return;
    if (writeIfChanged(path.join(ART_DST, f), fs.readFileSync(path.join(ART_SRC, f)))) changed.push(path.relative(ROOT, path.join(ART_DST, f)));
  });
  return { changed: changed, moduleBytes: mod.length, cssBytes: css.length, js: js, css: css };
}
module.exports = { build, between, panelCss, M0, M1, C0, C1 };
if (require.main === module) {
  const r = build();
  console.log("build_panel_pstyle: module " + r.moduleBytes + " bytes, css " + r.cssBytes + " bytes; " + (r.changed.length ? "wrote " + r.changed.join(", ") : "nothing changed"));
}
