#!/usr/bin/env node
"use strict";
/* Build panel/js/hnk_imagine.js + the Imagine rules in panel/styles.css + panel/icons/imagine/
   from the web app — the Imagine page (6.29.0 wave) is ONE module that runs on both surfaces.

   The app's index.html carries the module between two comment markers, IMAGINE_MODULE and
   /IMAGINE_MODULE
   (IMAGINE_DATA — four tools, their templates in nine languages, the prompt frame — and the
   IMAGINE UI, which draws the hub and the tool view into a root element and asks a host adapter
   for strings, icons, assets, files, the RunningHub call, the gallery and the export). The panel
   gets that block byte for byte, plus one line that hangs it on globalThis.HNK. Its CSS is the
   app's block between the IMAGINE_CSS markers with the app's colour tokens renamed to the panel's
   (the values are identical — panel/styles.css :root copies the app's) and the page id renamed.
   The card art and template thumbnails are copied so the two surfaces show the same pictures.

   Idempotent: running it on a clean tree changes nothing (the pre-commit check relies on that).
   Usage: node tools/build_panel_imagine.js
   test/verify_imagine_w1.js re-runs this and fails on drift. */
const fs = require("fs");
const path = require("path");
const ROOT = path.join(__dirname, "..");
const APP = path.join(ROOT, "docs", "app", "index.html");
const OUT_JS = path.join(ROOT, "panel", "js", "hnk_imagine.js");
const OUT_CSS = path.join(ROOT, "panel", "styles.css");
const ART_SRC = path.join(ROOT, "docs", "app", "lib", "wf", "imagine");
const ART_DST = path.join(ROOT, "panel", "icons", "imagine");

const M0 = "/* ---- IMAGINE_MODULE ---- */", M1 = "/* ---- /IMAGINE_MODULE ---- */";
const C0 = "/* ---- IMAGINE_CSS ---- */", C1 = "/* ---- /IMAGINE_CSS ---- */";

function between(src, a, b, what) {
  const i = src.indexOf(a); if (i < 0) throw new Error(what + ": start marker missing " + a);
  const j = src.indexOf(b, i); if (j < 0) throw new Error(what + ": end marker missing " + b);
  if (src.indexOf(a, i + 1) >= 0) throw new Error(what + ": start marker appears twice");
  return src.slice(i, j + b.length);
}
/* the app's tokens → the panel's names for the same values (panel/styles.css :root, v6.51) */
const TOKENS = [["var(--gold-hi)", "var(--accent-h)"], ["var(--gold)", "var(--accent)"], ["var(--cream)", "var(--text)"], ["var(--ink)", "var(--bg)"]];
function panelCss(appCss) {
  let s = appCss;
  TOKENS.forEach(function (p) { s = s.split(p[0]).join(p[1]); });
  s = s.split("#pgImagine").join("#pageImagine");
  return s;
}
let DRY = false;   /* build({ dry: true }) only reports what differs — the test's drift check */
function writeIfChanged(file, content) {
  const cur = fs.existsSync(file) ? fs.readFileSync(file) : null;
  const buf = Buffer.isBuffer(content) ? content : Buffer.from(content, "utf8");
  if (cur && cur.equals(buf)) return false;
  if (DRY) return true;
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, buf);
  return true;
}
function build(opts) {
  DRY = !!(opts && opts.dry);
  const app = fs.readFileSync(APP, "utf8");
  const mod = between(app, M0, M1, "module");
  const js = "/* GENERATED by tools/build_panel_imagine.js from docs/app/index.html — do not edit by hand.\n" +
    "   The web app's Imagine module (6.29.0 wave), byte for byte: IMAGINE_DATA (four tools, their\n" +
    "   templates in nine languages, the prompt frame) and the IMAGINE UI. main.js hands it the panel's\n" +
    "   host adapter (imagineHost) and a root element; nothing here knows it is inside Photoshop. */\n" +
    mod + "\n" +
    "globalThis.HNK = globalThis.HNK || {};\n" +
    "globalThis.HNK.imagine = IMAGINE;\n" +
    "globalThis.HNK.imagineData = IMAGINE_DATA;\n";
  const changed = [];
  if (writeIfChanged(OUT_JS, js)) changed.push("panel/js/hnk_imagine.js");
  /* CSS: replace the block between the markers, or append it once */
  const css = panelCss(between(app, C0, C1, "css"));
  let cur = fs.readFileSync(OUT_CSS, "utf8");
  let next;
  if (cur.indexOf(C0) >= 0) next = cur.replace(between(cur, C0, C1, "panel css"), css);
  else next = cur.replace(/\s*$/, "\n\n") + css + "\n";
  if (next !== cur) { if (!DRY) fs.writeFileSync(OUT_CSS, next); changed.push("panel/styles.css"); }
  /* art: every jpg under docs/app/lib/wf/imagine (cards) and its th/ (template thumbnails) */
  const copy = function (src, dst) {
    if (!fs.existsSync(src)) return;
    fs.readdirSync(src).forEach(function (f) {
      const s = path.join(src, f);
      if (fs.statSync(s).isDirectory()) return;
      if (!/\.(jpe?g|png|webp)$/i.test(f)) return;
      if (writeIfChanged(path.join(dst, f), fs.readFileSync(s))) changed.push(path.relative(ROOT, path.join(dst, f)));
    });
  };
  copy(ART_SRC, ART_DST);
  copy(path.join(ART_SRC, "th"), path.join(ART_DST, "th"));
  return { changed: changed, moduleBytes: mod.length, cssBytes: css.length, js: js, css: css };
}
module.exports = { build, between, panelCss, M0, M1, C0, C1 };
if (require.main === module) {
  const r = build();
  console.log("build_panel_imagine: module " + r.moduleBytes + " bytes, css " + r.cssBytes + " bytes; " + (r.changed.length ? "wrote " + r.changed.join(", ") : "nothing changed"));
}
